const test=require('node:test'),assert=require('node:assert/strict');
const {createActivityCombat}=require('../utils/activityCombat');
const {applyDamage}=require('../utils/activityDamage');
const {combatSpec}=require('../activity/native-combat.cjs');
const {immobilized,movementFactor}=require('../activity/combat-status.cjs');
const grid={origin:{x:-10,z:-10},step:1,width:25,height:25,cells:Array(625).fill(0),spawn:{x:0,y:0,z:0}};
function fixture(character,extra={}){let time=0;const actor={id:'a',character,x:0,y:0,z:0,hp:100},enemy={id:'e',enemy:true,x:3,y:0,z:0,hp:100};const room=new Map([['a',actor],['e',enemy]]),combat=createActivityCombat({grid,now:()=>time,...extra});return {actor,enemy,room,combat,cast(kind='craft',target){return combat.action(actor,{id:kind+time,kind,target,aim:{x:3,y:0,z:0}},room);},tick(t){time=t;combat.tick(room);},get time(){return time;}};}
test('Bind Whip slows only targets struck on its chosen segment, then expires',()=>{const f=fixture('Scherazard');f.room.set('side',{id:'side',enemy:true,x:2,y:0,z:3,hp:100});assert.ok(f.cast().combatId);f.tick(400);assert.equal(f.enemy.hp,70);assert.equal(movementFactor(f.enemy,400),.45);assert.equal(movementFactor(f.enemy,4400),1);assert.equal(f.room.get('side').hp,100);});
test('Requiem sweeps successive directions: a target is only hit when its sector is fired',()=>{const f=fixture('Olivier');for(const [id,x,z]of [['behind',-3,0],['side',0,4],['far',9,0]])f.room.set(id,{id,x,y:0,z,hp:100});assert.ok(f.cast().combatId);f.tick(320);assert.equal(f.enemy.hp,100);assert.equal(f.room.get('side').hp,100);f.tick(820);assert.equal(f.enemy.hp,52);assert.equal(f.enemy.damageEvents.length,1);assert.equal(f.room.get('behind').hp,100);f.tick(1320);assert.equal(f.room.get('side').hp,52);f.tick(1820);assert.equal(f.room.get('behind').hp,52);f.tick(5200);assert.equal(f.enemy.hp,52);assert.equal(f.room.get('far').hp,100);});
test('Tita cannon explodes at the landing point and damages nearby enemies, not before impact',()=>{const f=fixture('Tita');f.room.set('near',{id:'near',enemy:true,x:3,y:0,z:1,hp:100});f.room.set('outside',{id:'outside',enemy:true,x:3,y:0,z:2,hp:100});assert.ok(f.cast('basic').combatId);const a=f.combat.snapshot().attacks[0];f.tick(a.impactAt-1);assert.equal(f.enemy.hp,100);f.tick(a.impactAt);assert.equal(f.enemy.hp,88);assert.equal(f.room.get('near').hp,88);assert.equal(f.room.get('outside').hp,100);});
test('Zin successful normal hits carry the native blue fist effect, misses produce none',()=>{const f=fixture('Zin');f.enemy.x=1.5;assert.ok(f.cast('basic').combatId);f.tick(150);assert.equal(f.enemy.damageEvents[0].nativeEffect,'Third/msc0614._ef');});
test('Sturm requires an enemy and stuns it only until the attack animation ends',()=>{const f=fixture('Kloe');assert.ok(f.cast('craft','e').error);f.enemy.x=1.5;assert.ok(f.cast().error);assert.ok(f.cast('craft','e').combatId);f.tick(400);assert.ok(immobilized(f.enemy,400));f.tick(800);assert.equal(f.enemy.hp,70);assert.ok(immobilized(f.enemy,1399));assert.equal(immobilized(f.enemy,1400),false);f.enemy.character='Joshua';assert.ok(f.combat.action(f.enemy,{id:'stunned',kind:'basic',aim:{x:0,y:0,z:0}},f.room).error);});
test('Lacrym requires explicit selection: self or living party member, never an enemy',()=>{const f=fixture('Kloe',{dungeon:{}});f.actor.hp=40;assert.ok(f.cast('art').error);assert.ok(f.cast('art','e').error);f.room.set('ally',{id:'ally',x:2,y:0,z:0,hp:50});assert.ok(f.cast('art','ally').combatId);f.tick(1000);assert.equal(f.room.get('ally').hp,85);assert.equal(f.actor.hp,40);const solo=fixture('Kloe');solo.actor.hp=40;assert.ok(solo.cast('art','a').combatId);solo.tick(1000);assert.equal(solo.actor.hp,75);});
test('Agate travels through an airborne arc, lands before the chosen impact point and damages there',()=>{const f=fixture('Agate');assert.ok(f.cast().combatId);f.tick(425);assert.ok(f.actor.x>0&&f.actor.x<3);assert.ok(f.actor.y>2);f.tick(650);assert.equal(f.actor.x,2.2);assert.equal(f.actor.y,0);assert.equal(f.enemy.hp,65);});
test('Smoke Cannon blinds a hit target for exactly five seconds',()=>{const f=fixture('Tita');f.cast();const impact=f.combat.snapshot().attacks[0].impactAt;f.tick(impact-1);assert.equal(f.enemy.blindUntil,undefined);f.tick(impact);assert.equal(f.enemy.blindUntil,impact+5000);assert.equal(f.enemy.hp,70);});
test('True Distend locks Zin until completion and grants 60% attack and damage reduction for ten seconds',()=>{const f=fixture('Zin');assert.ok(f.cast().combatId);assert.equal(f.actor.combatLockedUntil,1400);f.tick(1399);assert.equal(f.actor.attackBuff,undefined);f.tick(1400);assert.equal(f.actor.attackBuff.amount,.6);assert.equal(applyDamage(f.actor,50,1400).damage,20);assert.equal(applyDamage(f.actor,50,11400).damage,50);f.enemy.x=2;f.tick(2000);assert.ok(f.cast('basic').combatId);f.tick(2150);assert.equal(f.enemy.hp,81);});
test('Forte and Crest buff their caster; Earth Guard blocks precisely one whole hit',()=>{for(const [name,field]of [['Agate','attackBuff'],['Zin','defenseBuff']]){const f=fixture(name);f.cast('art');f.tick(1000);assert.equal(f.actor[field].amount,.25);assert.equal(f.actor[field].until,11000);}const f=fixture('Kevin');f.cast('art');f.tick(1000);assert.equal(applyDamage(f.actor,99,1000).damage,0);assert.equal(f.actor.guard,null);assert.equal(applyDamage(f.actor,12,1001).damage,12);});
test('Gorgon Arrow immobilizes a hit enemy for three seconds and cannot bypass an Earth Guard',()=>{const f=fixture('Kevin');f.cast();const at=f.combat.snapshot().attacks[0].impactAt;f.tick(at);assert.ok(immobilized(f.enemy,at+2999));assert.equal(immobilized(f.enemy,at+3000),false);const g=fixture('Kevin');g.enemy.guard={until:10000};g.cast();g.tick(1000);assert.equal(g.enemy.hp,100);assert.equal(g.enemy.stoneUntil,undefined);});
test('Joshua casts native Soul Blur and Scherazard inherits his wind art',()=>{assert.equal(combatSpec('Joshua','art').nativeEffect,'SC/mg065_0._ef');assert.equal(combatSpec('Scherazard','art').nativeEffect,'SC/mg050_0._ef');});

test('Sturm tracks a moving Mishy instead of striking the empty location selected earlier',()=>{const f=fixture('Kloe',{dungeon:{},canDamage:(_a,b)=>b.enemy});f.enemy.x=1.4;assert.ok(f.cast('craft','e').combatId);f.enemy.x=1.6;f.enemy.z=.4;f.tick(400);assert.equal(f.enemy.hp,90);assert.ok(immobilized(f.enemy,400));f.tick(800);assert.equal(f.enemy.hp,70);});
test('cannon shots hit their landing area and buffs retain their visual events for ten seconds',()=>{const f=fixture('Tita');f.room.set('near',{id:'near',enemy:true,x:3,y:0,z:1.2,hp:100});f.cast('basic');const at=f.combat.snapshot().attacks[0].impactAt;f.tick(at-1);assert.equal(f.enemy.hp,100);f.tick(at);assert.equal(f.enemy.hp,88);assert.equal(f.room.get('near').hp,88);for(const[hero,kind]of[['Agate','art'],['Zin','art'],['Zin','craft']]){const g=fixture(hero);g.cast(kind);const a=g.combat.snapshot().attacks[0];assert.equal(a.endsAt-a.impactAt,10000);g.tick(a.impactAt+9999);assert.ok(g.combat.snapshot().attacks.some(e=>e.id===a.id));}});

test('a weaker buff cannot extend True Distend and petrification stops horizontal jump travel',()=>{
 const {applyBuff,applyStatus}=require('../activity/combat-status.cjs'),{jumpPosition}=require('../activity/dungeon-mechanics.cjs');
 const p={x:1,z:2,jump:{origin:{x:0,y:0,z:0},started:0,dx:1,dz:0}};applyBuff(p,{buffDefense:.6,buffDuration:10000},0);applyBuff(p,{buffDefense:.25,buffDuration:10000},9000);assert.equal(p.defenseBuff.until,10000);
 applyStatus(p,{status:'stone',statusDuration:3000},400);const before=jumpPosition(p.jump,400),after=jumpPosition(p.jump,800);assert.equal(before.x,1);assert.equal(after.x,1);assert.equal(after.z,2);assert.notEqual(before.y,after.y);
});
