const test=require('node:test'),assert=require('node:assert/strict');
const {createActivityCombat}=require('../utils/activityCombat');
const {createActivityService}=require('../utils/activityService');
const {createActivityLobby}=require('../utils/activityLobby');
const {createActivityRoleplay,gifInfo}=require('../utils/activityRoleplay');
const {createRoleplayDiscordSender}=require('../utils/activityRoleplayDiscord');
const {GIFEncoder}=require('gifenc');
const grid={origin:{x:-12,z:-12},step:1,width:25,height:25,cells:Array(625).fill(0),spawn:{x:0,y:0,z:0}};
function fixture(extra={}){let clock=1000;const players=new Map([['renne',{id:'renne',character:'Renne',x:0,y:0,z:0,hp:100}],['victim',{id:'victim',character:'Joshua',x:2,y:0,z:0,hp:100}]]);const crafts=[];const combat=createActivityCombat({grid,now:()=>clock,onCraft:e=>crafts.push(e),...extra});return {players,combat,crafts,tick(ms){clock+=ms;combat.tick(players);},start(kind,aim={x:2,y:0,z:0},id='attack-'+kind){return combat.action(players.get('renne'),{id,kind,aim},players);}};}
test('Renne melee deals server-owned damage once, in front and on the same floor',()=>{const f=fixture();f.players.set('behind',{id:'behind',x:-1,y:0,z:0,hp:100});f.players.set('above',{id:'above',x:2,y:2,z:0,hp:100});f.players.set('watch',{id:'watch',x:2,y:0,z:0,hp:100,spectator:true});assert.ok(f.start('basic').combatId);f.tick(299);assert.equal(f.players.get('victim').hp,100);f.tick(1);assert.equal(f.players.get('victim').hp,88);f.tick(1000);assert.equal(f.players.get('victim').hp,88);for(const id of ['behind','above','watch'])assert.equal(f.players.get(id).hp,100);});
test('art and craft have distinct damage and the target can dodge before impact',()=>{for(const [kind,damage]of [['art',20],['craft',30]]){const f=fixture();assert.ok(f.start(kind).combatId);f.tick(1800);assert.equal(f.players.get('victim').hp,100-damage);assert.equal(f.crafts.length,kind==='craft'?1:0);}const f=fixture();f.start('craft');f.players.get('victim').z=6;f.tick(1800);assert.equal(f.players.get('victim').hp,100);});
test('character, dead, spectator, aim, cooldown and wall checks cannot be bypassed',()=>{const f=fixture();const p=f.players.get('renne');p.character='Estelle';assert.ok(f.start('basic').error);p.character='Renne';p.hp=0;assert.ok(f.start('basic').error);p.hp=100;p.spectator=true;assert.ok(f.start('basic').error);p.spectator=false;assert.ok(f.start('craft',{x:Infinity,y:0,z:0}).error);assert.ok(f.start('craft',{x:2,y:20,z:0}).error);assert.ok(f.start('basic').combatId);assert.ok(f.start('craft',undefined,'another-id').error);f.tick(700);assert.ok(f.start('basic',undefined,'next-id').combatId);const wall=fixture({geometry:{floor:()=>0,sweep:(a,b)=>a.x<1&&b.x>1?{point:{x:1,y:.85,z:0},normal:{x:-1,y:0,z:0}}:null}});wall.start('basic');wall.tick(400);assert.equal(wall.players.get('victim').hp,100);});
test('death or departure before impact cancels damage, and deaths use ten seconds',()=>{const f=fixture();f.start('craft');f.players.get('renne').hp=0;f.tick(1800);assert.equal(f.players.get('victim').hp,100);assert.equal(f.combat.snapshot().attacks[0].cancelled,true);const g=fixture();g.players.get('victim').hp=10;g.start('basic');g.tick(300);assert.equal(g.players.get('victim').hp,0);assert.equal(g.players.get('victim').deadUntil,11300);});
test('service retries, including older action IDs, do not repeat chat or crafts',async()=>{let clock=1000;const speech=[],crafts=[];const service=createActivityService({grid,combatEnabled:true,now:()=>clock,resolveCharacter:async()=> 'Renne',onSay:e=>speech.push(e),onCraft:e=>crafts.push(e)});const session=await service.join({id:'account',channel:'map:arena'});const token=session.activity_token;const action={id:'say-first',type:'say',text:'Bonjour @everyone'};await service.state(token,{x:0,z:0,action});clock+=1001;await service.state(token,{x:0,z:0,action:{...action,id:'say-second'}});await service.state(token,{x:0,z:0,action});await new Promise(resolve=>setImmediate(resolve));assert.equal(speech.length,2);const craft={id:'craft-first',type:'attack',kind:'craft',aim:{x:3,y:0,z:0},damage:999};await service.state(token,{x:0,z:0,action:craft});await service.state(token,{x:0,z:0,action:craft});assert.equal(crafts.length,1);const locked=await service.state(token,{x:1,z:0});assert.equal(locked.position.x,0);assert.equal(locked.health.canMove,false);});
test('arena combat events contain anonymous aliases, not account IDs',async()=>{let clock=1000;const lobby=createActivityLobby({grid,now:()=>clock,resolveCharacter:async id=>id==='private-one'?'Renne':'Joshua',arena:{grid,combatEnabled:true,spawns:[{x:0,y:0,z:0},{x:2,y:0,z:0}]}});lobby.createDuel({id:'match',players:['private-one','private-two'],channel:'channel'});lobby.joinDuel('match','private-one');lobby.joinDuel('match','private-two');const a=await lobby.join({id:'private-one',channel:'channel'}),b=await lobby.join({id:'private-two',channel:'channel'});await lobby.state(a.activity_token);await lobby.state(b.activity_token);await lobby.state(a.activity_token,{x:0,z:0,action:{id:'anon-hit',type:'attack',kind:'basic',aim:{x:2,y:0,z:0}}});clock+=400;const result=await lobby.state(b.activity_token);assert.equal(result.health.hp,88);assert.match(result.combat.attacks[0].actor,/^avatar:/);assert.match(result.combat.attacks[0].hits[0].id,/^avatar:/);assert.equal(JSON.stringify(result).includes('private-'),false);});
function animatedGif(frames=4,width=96,height=64){const gif=GIFEncoder();for(let i=0;i<frames;i++)gif.writeFrame(new Uint8Array(width*height).fill(i%2),width,height,{palette:[[0,0,0],[255,0,100]],delay:100});gif.finish();return Buffer.from(gif.bytes());}
test('only the craft owner can publish a bounded animated GIF, once even concurrently',async()=>{const posts=[];let release;const relay=createActivityRoleplay({send:payload=>{posts.push(payload);return new Promise(resolve=>release=resolve);},setTimer:()=>null});relay.craft({id:'craft-id',actor:'account',character:'Renne',technique:'Cercle sanglant'});const body={id:'craft-id',gif:animatedGif().toString('base64')};await assert.rejects(()=>relay.capture('other-account',body),{status:403});await assert.rejects(()=>relay.capture('account',{...body,gif:Buffer.from('not-gif').toString('base64')}),{status:400});const one=relay.capture('account',body),two=relay.capture('account',body);await new Promise(resolve=>setImmediate(resolve));assert.equal(posts.length,1);release();await Promise.all([one,two]);await relay.capture('account',body);assert.equal(posts.length,1);assert.equal(posts[0].text,'Renne lance Cercle sanglant.');assert.equal(gifInfo(posts[0].gif).frames,4);});
test('GIF validation rejects excessive dimensions, frames and truncation',()=>{assert.throws(()=>gifInfo(animatedGif(4,321,64)));assert.throws(()=>gifInfo(animatedGif(25)));assert.throws(()=>gifInfo(animatedGif().subarray(0,30)));assert.throws(()=>gifInfo(animatedGif(1)));});
test('all chat text is published in bounded chunks under character identity',async()=>{const posts=[];const relay=createActivityRoleplay({send:async p=>posts.push(p),setTimer:()=>null});const event={id:'speech',character:'Renne',text:'x'.repeat(4000)};await relay.speech(event);await relay.speech(event);assert.equal(posts.length,3);assert.equal(posts.map(p=>p.text).join(''),event.text);assert.ok(posts.every(p=>p.character==='Renne'&&p.text.length<=1800));});
test('Discord sender never replies, pings, exposes an account or uses a webhook in another channel',async()=>{const posts=[],fallback=[];class Hook{async fetch(){return {channelId:'roleplay'};}async send(p){posts.push(p);}}const sender=createRoleplayDiscordSender({WebhookClient:Hook,webhookUrl:'fixture',channelId:'roleplay',baseUrl:'https://example.test',client:{}});await sender({character:'Renne',text:'@everyone',gif:animatedGif()});assert.equal(posts[0].username,'Renne');assert.deepEqual(posts[0].allowedMentions.parse,[]);assert.equal(posts[0].reply,undefined);assert.equal(posts[0].files[0].name,'craft.gif');class Wrong extends Hook{async fetch(){return {channelId:'other'};}}const safe=createRoleplayDiscordSender({WebhookClient:Wrong,webhookUrl:'fixture',channelId:'roleplay',client:{channels:{fetch:async id=>{assert.equal(id,'roleplay');return {guild:{},isTextBased:()=>true,send:async p=>fallback.push(p)};}}}});await safe({character:'Renne',text:'Bonjour'});assert.equal(posts.length,1);assert.equal(fallback[0].content,'**Renne** : Bonjour');});
