const test=require('node:test'),assert=require('node:assert/strict');
const {createDungeonJumps}=require('../utils/activityDungeonJumps'),{createDungeonFire}=require('../utils/activityDungeonFire'),{createActivityService}=require('../utils/activityService'),{createActivityEnemies}=require('../utils/activityEnemies'),{createActivityGeometry}=require('../utils/activityGeometry');
const {jumpPosition,jumpDisplayPosition,inSector}=require('../activity/dungeon-mechanics.cjs');
const grid={origin:{x:0,z:0},step:.25,width:60,height:20,cells:Array(1200).fill(0),spawn:{x:1,y:0,z:2}};
const user=(id='one')=>({id,character:'Renne',x:1,y:0,z:2,hp:100});
test('jump is a bounded server parabola, lands across a void and cannot be repeated in midair',()=>{let clock=1000;const g={...grid,cells:[...grid.cells]};for(let z=0;z<20;z++)for(let x=9;x<17;x++)g.cells[z*60+x]=null;const jumps=createDungeonJumps({grid:g,now:()=>clock}),p=user(),players=new Map([[p.id,p]]);assert.deepEqual(jumps.action(p,{id:'jump',direction:{dx:1,dz:0}}),{});assert.ok(jumps.action(p,{id:'again',direction:{dx:1,dz:0}}).error);clock+=500;jumps.tick(players);assert.ok(p.y>1.6);assert.equal(p.x,3.25);clock+=500;jumps.tick(players);assert.equal(p.jump,null);assert.equal(p.x,5.5);assert.equal(p.y,0);assert.equal(p.hp,100);assert.ok(jumps.action(p,{id:'early'}).error);});
test('a missed jump returns to its takeoff platform with damage, and walls block it',()=>{let clock=1000;const g={...grid,cells:grid.cells.map((v,i)=>i%60>8?null:v)},p=user(),jumps=createDungeonJumps({grid:g,now:()=>clock}),room=new Map([[p.id,p]]);jumps.action(p,{id:'fall',direction:{dx:1,dz:0}});clock+=1350;jumps.tick(room);assert.equal(p.x,1);assert.equal(p.hp,80);assert.equal(p.jump,null);clock+=1500;const blocked=createDungeonJumps({grid,now:()=>clock,geometry:{sweep:()=>({distance:.1})}});blocked.action(p,{id:'wall',direction:{dx:1,dz:0}});clock+=200;blocked.tick(room);assert.equal(p.x,1);assert.equal(p.hp,60);});
test('real generated islands are reachable by jumping, without crossing walls or permitting an ordinary walk',()=>{for(let floor=1;floor<=3;floor++){const root='../activity/assets/sky/tower'+floor+'/',grid=require(root+'navigation.json'),layout=require(root+'layout.json'),geometry=createActivityGeometry(JSON.parse(require('node:fs').readFileSync(require('node:path').join(__dirname,root+'anterose.gltf'),'utf8')));assert.equal(layout.islands.length,2);for(const link of layout.jumpLinks){let time=1000;const p={...user(),...link.from},room=new Map([[p.id,p]]),jumps=createDungeonJumps({grid,geometry,now:()=>time}),length=Math.hypot(link.to.x-link.from.x,link.to.z-link.from.z);assert.ok(length<4.5);const mid={x:(link.to.x+link.from.x)/2,z:(link.to.z+link.from.z)/2};assert.equal(geometry.floor(mid.x,mid.z,.5),null);jumps.action(p,{id:'island',direction:{dx:(link.to.x-link.from.x)/length,dz:(link.to.z-link.from.z)/length}});for(let i=0;i<20;i++){time+=50;jumps.tick(room);}assert.equal(p.hp,100,'clear takeoff opening');assert.equal(p.jump,null);assert.ok(Math.hypot(p.x-link.from.x,p.z-link.from.z)>4.4);assert.ok(Math.abs(geometry.floor(p.x,p.z,.5))<.03);}}});
test('server service ignores forged airborne coordinates and shares the jump with other players',async()=>{let time=1000;const service=createActivityService({grid,resolveCharacter:async()=> 'Renne',now:()=>time,combatEnabled:true,dungeon:{traps:[]},residents:{npcs:[],disablePoms:true}}),a=await service.join({id:'a',channel:'tower'}),b=await service.join({id:'b',channel:'tower'});await service.state(a.activity_token);await service.state(b.activity_token);const result=await service.state(a.activity_token,{x:999,y:999,z:999,action:{id:'jump',type:'jump',direction:{dx:1,dz:0}}});assert.ok(result.health.jump);assert.equal(result.position.x,1);time+=500;const other=await service.state(b.activity_token);assert.ok(other.joueurs.find(p=>p.id==='a').y>1.6);const forged=await service.state(a.activity_token,{x:999,y:999,z:999});assert.equal(forged.position.x,3.25);time+=500;const landed=await service.state(a.activity_token,{x:999,y:999,z:999});assert.equal(landed.health.jump,null);assert.equal(landed.position.x,5.5);});
test('filled Mishy sector hits in front, spares targets behind or airborne and has a shorter windup',()=>{let time=1000;const p={...user(),x:3,z:2},ai=createActivityEnemies({grid,now:()=>time,spawns:[{x:2,y:0,z:2}]}),players=new Map([[p.id,p]]);ai.tick(players);const a=ai.snapshot()[0].attack;assert.equal(a.at-a.started,420);assert.ok(inSector(p,a));assert.equal(inSector({...p,x:1},a),false);assert.equal(inSector({...p,y:1.65},a),false);time=a.at;ai.tick(players);assert.equal(p.hp,90);});
test('low fire is jumped over, high fire misses grounded players but hits airborne ones, with swept collision and no repeat hit',()=>{for(const [height,y,hit]of [[.45,0,true],[.45,1.65,false],[2.35,0,false],[2.35,1.65,true]]){let time=1000;const p={...user(),x:4,y},room=new Map([[p.id,p]]),fire=createDungeonFire({now:()=>time});fire.launch({x:0,y:height,z:2},{x:1,y:0,z:0},{speed:8});time+=1000;fire.tick(room);assert.equal(p.hp,hit?88:100);fire.tick(room);assert.equal(p.hp,hit?88:100);}});
test('ranged Mishy fires at a locked ground direction; traps share bounded rows and walls stop fire',()=>{let time=1000;const fire=createDungeonFire({now:()=>time}),p={...user(),x:5},room=new Map([[p.id,p]]),ai=createActivityEnemies({grid,now:()=>time,fire,spawns:[{x:2,y:0,z:2,ranged:true}]});ai.tick(room);assert.equal(ai.snapshot()[0].character,'MishyArdent');assert.equal(ai.snapshot()[0].attack,null);assert.equal(fire.snapshot().length,3);time+=650;ai.tick(room);assert.equal(fire.snapshot().length,6);time+=600;fire.tick(room);assert.ok(p.hp<100);const hp=p.hp;const wall=createDungeonFire({now:()=>time,geometry:{sweep:()=>({distance:.1})}});wall.launch({x:0,y:.45,z:2},{x:1,y:0,z:0});time+=1000;wall.tick(room);assert.equal(p.hp,hp);assert.equal(wall.snapshot().length,0);const trap=createDungeonFire({now:()=>time,traps:[{id:'trap',start:{x:0,y:0,z:0},end:{x:10,y:0,z:0},width:3,height:2.35,period:3200,phase:0}]});time+=3200;trap.tick(room);assert.ok(trap.snapshot().length>0&&trap.snapshot().length<=5);const n=trap.snapshot().length;trap.tick(room);assert.equal(trap.snapshot().length,n);});

test('a delayed jump lands normally and a long absence cannot create unbounded collision work or expired fire damage',()=>{let time=1000,calls=0;const geometry={sweep:()=>{calls++;return null;}},jumps=createDungeonJumps({grid,geometry,now:()=>time}),p=user(),room=new Map([[p.id,p]]);jumps.action(p,{id:'delayed',direction:{dx:1,dz:0}});time+=1200;jumps.tick(room);assert.equal(p.x,5.5);assert.equal(p.hp,100);assert.equal(p.jump,null);time+=2000;jumps.action(p,{id:'absent',direction:{dx:1,dz:0}});time+=3600000;jumps.tick(room);assert.equal(p.jump,null);assert.equal(p.hp,100);assert.ok(calls<=50);const fire=createDungeonFire({now:()=>time});fire.launch({x:0,y:.45,z:2},{x:1,y:0,z:0});time+=3600000;fire.tick(room);assert.equal(p.hp,100);assert.equal(fire.snapshot().length,0);});

test('client prediction stays on the landing floor while waiting for confirmation instead of sinking through it',()=>{const jump={started:1000,origin:{x:1,y:0,z:2},dx:0,dz:0};assert.equal(jumpDisplayPosition(grid,jump,2400).y,0);assert.ok(jumpDisplayPosition(grid,jump,1500).y>1.6);const voidGrid={...grid,cells:Array(1200).fill(null)};assert.ok(jumpDisplayPosition(voidGrid,jump,2400).y<0);});
