const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {createActivityLobby}=require('../utils/activityLobby'),{createActivityGeometry}=require('../utils/activityGeometry');
const floors=[1,2,3].map(i=>{const p=path.join(__dirname,'../activity/assets/sky/tower'+i);return{grid:require(p+'/navigation.json'),layout:require(p+'/layout.json'),geometry:createActivityGeometry(JSON.parse(fs.readFileSync(p+'/anterose.gltf')))};});
const simple={origin:{x:0,z:0},step:1,width:3,height:3,cells:Array(9).fill(0),spawn:{x:1,y:0,z:1}};
test('all three seeded floors are distinct, connected and agree with their actual surfaces',()=>{
 const fingerprints=new Set();for(const f of floors){const g=f.grid,open=g.cells.map((v,i)=>v===null?-1:i).filter(i=>i>=0),seen=new Set([open[0]]),queue=[open[0]],links=new Map();for(const link of f.layout.jumpLinks??[]){const ix=p=>Math.round((p.z-g.origin.z)/g.step)*g.width+Math.round((p.x-g.origin.x)/g.step),a=ix(link.from),b=ix(link.to);links.set(a,b);links.set(b,a);}for(const i of queue)for(const j of [i-1,i+1,i-g.width,i+g.width,links.get(i)].filter(Number.isInteger))if(j>=0&&j<g.cells.length&&g.cells[j]!==null&&!seen.has(j)&&(links.get(i)===j||Math.abs(j%g.width-i%g.width)<=1)){seen.add(j);queue.push(j);}assert.equal(seen.size,open.length);for(const p of [f.layout.start,f.layout.exit,...f.layout.rooms])assert.ok(Math.abs(f.geometry.floor(p.x,p.z,p.y+.5)-p.y)<.03);fingerprints.add(JSON.stringify(f.layout.tiles));}assert.equal(fingerprints.size,3);
});
test('tower shares each floor across Discord sources and unites all floors in one anonymous team',async()=>{
 let clock=1000;const lobby=createActivityLobby({grid:simple,tower:floors,now:()=>clock,resolveCharacter:async id=>id==='private-one'?'Renne':'Joshua'});lobby.enterTower('private-one');lobby.enterTower('private-two',2);const a=await lobby.join({id:'private-one',channel:'dm'}),b=await lobby.join({id:'private-two',channel:'guild'});await lobby.state(b.activity_token);const state=await lobby.state(a.activity_token);assert.equal(state.team.length,2);assert.deepEqual(state.team.map(p=>p.floor).sort(),[1,2]);assert.equal(JSON.stringify(state.team).includes('private-'),false);lobby.enterTower('private-two',1);const other=await lobby.state(b.activity_token);assert.equal(other.map,'tower1');assert.equal(other.joueurs.length,2);const back=await lobby.state(b.activity_token,{x:1,y:0,z:1,action:{id:'leave',type:'leave_map'}});assert.equal(back.map,'anterose');assert.equal((await lobby.state(a.activity_token)).team.length,1);
});
test('tower combat plays and cooldowns apply without friendly damage, Poms or NPCs',async()=>{
 let clock=1000;const lobby=createActivityLobby({grid:simple,tower:[{grid:simple,layout:{start:simple.spawn,exit:{x:2,y:0,z:2}}}],now:()=>clock,resolveCharacter:async id=>id==='a'?'Renne':'Joshua'});lobby.enterTower('a');lobby.enterTower('b');const a=await lobby.join({id:'a',channel:'dm'}),b=await lobby.join({id:'b',channel:'guild'});let state=await lobby.state(a.activity_token,{x:1,y:0,z:1,action:{id:'swing',type:'attack',kind:'craft',aim:{x:2,y:0,z:1}}});assert.ok(state.combat.attacks.length);assert.equal(state.poms.length,0);assert.equal(state.npcs.length,0);clock+=2000;state=await lobby.state(b.activity_token);assert.ok(state.joueurs.every(p=>p.hp===100));assert.equal(state.combat.attacks[0].hits.length,0);
});
test('stairs reject remote and invalid requests; accepted transfers are idempotent and return to the exit below',async()=>{
 const f=[1,2,3].map((_,i)=>({grid:simple,layout:{start:simple.spawn,exit:{x:1,y:0,z:1}}}));const lobby=createActivityLobby({grid:simple,tower:f,resolveCharacter:async()=> 'Estelle'});const home=await lobby.join({id:'a',channel:'dm'});assert.equal((await lobby.state(home.activity_token,{x:1,y:0,z:1,action:{id:'home-step',type:'tower_step',target:'up'}})).map,'anterose');lobby.enterTower('a');await lobby.state(home.activity_token);const packet={x:1,y:0,z:1,action:{id:'stairs-one',type:'tower_step',target:'up'}};assert.equal((await lobby.state(home.activity_token,packet)).map,'tower2');assert.equal((await lobby.state(home.activity_token,packet)).map,'tower2');assert.equal((await lobby.state(home.activity_token,{x:1,y:0,z:1,action:{id:'stairs-two',type:'tower_step',target:'up'}})).map,'tower3');assert.ok((await lobby.state(home.activity_token,{x:1,y:0,z:1,action:{id:'past-top',type:'tower_step',target:'up'}})).actionResult.error);const down=await lobby.state(home.activity_token,{x:1,y:0,z:1,action:{id:'back-down',type:'tower_step',target:'down'}});assert.equal(down.map,'tower2');assert.deepEqual(down.position,f[1].layout.exit);
});

test('Capel entrance requires proximity and cannot teleport an unauthenticated user',async()=>{const lobby=createActivityLobby({grid:simple,tower:floors,resolveCharacter:async()=> 'Estelle'}),s=await lobby.join({id:'a',channel:'dm'}),{createActivityTerminal}=require('../utils/activityTerminal');const terminal={position:{x:1,y:0,z:1}};const menu=createActivityTerminal({lobby,terminal,duels:{pending:()=>[]},client:{},resolveCharacter:async()=> 'Estelle',assignedCharacters:async()=>[]});await assert.rejects(()=>menu.action('invalid',{request:'tower-invalid',action:'tower'}),{status:401});const distant=createActivityTerminal({lobby,terminal:{position:{x:20,y:0,z:20}},duels:{},client:{}});await assert.rejects(()=>distant.action(s.activity_token,{request:'tower-remote',action:'tower'}),{status:403});await menu.action(s.activity_token,{request:'tower-valid',action:'tower'});const state=await lobby.state(s.activity_token);assert.equal(state.map,'tower1');const far=await lobby.state(s.activity_token,{...state.position,action:{id:'remote-stairs',type:'tower_step',target:'up'}});assert.equal(far.map,'tower1');assert.ok(far.actionResult.error);});

test('Esmelas uses separate native FC materials and bridges that connect varied platforms above empty space',()=>{for(const f of floors){assert.equal(f.layout.version,2);assert.ok(f.layout.platforms.length>=7);assert.ok(f.layout.platforms.some(p=>Math.max(p.rx,p.rz)>6));assert.ok(f.layout.platforms.some(p=>p.walls.length));const root=path.join(__dirname,'../activity/assets/sky/tower'+f.layout.floor);const model=JSON.parse(fs.readFileSync(root+'/anterose.gltf'));assert.ok(model.images.every(i=>i.uri.startsWith('C04C')));assert.ok(model.materials.length>=6&&model.materials.length<=9);assert.ok(f.grid.cells.some(y=>y===null));for(const bridge of f.layout.bridges){const x=(bridge.start[0]+bridge.end[0])/2,z=(bridge.start[1]+bridge.end[1])/2;assert.ok(Math.abs(f.geometry.floor(x,z,.5)-bridge.deckHeight)<.001);const index=Math.round((z-f.grid.origin.z)/f.grid.step)*f.grid.width+Math.round((x-f.grid.origin.x)/f.grid.step);assert.equal(f.grid.cells[index],bridge.deckHeight);}}});

test('tower enemies are shared between sessions while the party contains only players',async()=>{const inhabited=floors.map(f=>({...f,enemySpawns:f.layout.rooms.slice(1,5)})),lobby=createActivityLobby({grid:simple,tower:inhabited,resolveCharacter:async()=> 'Renne'});lobby.enterTower('a');lobby.enterTower('b');const a=await lobby.join({id:'a',channel:'dm'}),b=await lobby.join({id:'b',channel:'guild'});const one=await lobby.state(a.activity_token),two=await lobby.state(b.activity_token);assert.equal(one.enemies.length,4);assert.deepEqual(one.enemies.map(e=>e.id),two.enemies.map(e=>e.id));assert.equal(two.team.length,2);assert.equal(two.team.some(p=>p.character==='Mishy'),false);assert.equal(two.joueurs.length,2);assert.ok(two.enemies.every(e=>e.character==='Mishy'&&e.maxHp===75));});
