const test=require('node:test'),assert=require('node:assert/strict');
const {createActivityCombat}=require('../utils/activityCombat'),{createActivityService}=require('../utils/activityService'),{createActivityLobby}=require('../utils/activityLobby'),{applyDamage}=require('../utils/activityDamage');
const {createMovingPlatforms,platformPosition}=require('../activity/moving-platforms.cjs'),{combatSpec,COMBAT}=require('../activity/native-combat.cjs');
const {createActivityEnemies}=require('../utils/activityEnemies'),{createDungeonFire}=require('../utils/activityDungeonFire');
const grid={origin:{x:0,z:0},step:.25,width:60,height:24,cells:Array.from({length:1440},(_,i)=>i%60<=12||i%60>=36?0:null),spawn:{x:2,y:0,z:2}};
const boat={id:'ferry',from:{x:2,z:2},to:{x:10,z:2},width:2.6,y:.12,speed:2,dwell:1000,phase:0};
const user=(id,character='Renne',x=2)=>({id,character,x,y:0,z:2,hp:100});
test('shuttle platforms wait at both docks, share an absolute cycle and carry riders without changing their offset',()=>{let clock=0;const sim=createMovingPlatforms({grid,definitions:[boat],now:()=>clock});const p=user('one'),room=new Map([[p.id,p]]);sim.tick(room);assert.equal(p.platformId,'ferry');clock=3000;sim.tick(room);assert.equal(p.x,6);assert.equal(p.y,.12);assert.equal(sim.navigation().cells[8*60+24],.12);assert.equal(sim.navigation().cells[8*60+16],null);const old={...p};p.jump={};clock=3500;sim.tick(room);assert.equal(p.x,old.x);assert.equal(p.platformId,null);assert.equal(platformPosition(boat,5000).x,10);assert.equal(platformPosition(boat,6000).x,10);assert.equal(platformPosition(boat,8000).x,6);assert.deepEqual(platformPosition(boat,3000),platformPosition(boat,13000));});
test('service validates relative walking on moving platforms, disembarking and forged platform offsets',async()=>{let clock=0;const service=createActivityService({grid,now:()=>clock,resolveCharacter:async()=> 'Renne',combatEnabled:true,dungeon:{movingPlatforms:[boat]},residents:{npcs:[],disablePoms:true}}),a=await service.join({id:'a',channel:'tower'});let r=await service.state(a.activity_token);assert.equal(r.position.y,.12);clock=1500;r=await service.state(a.activity_token,{x:999,z:999,platform:{id:'ferry',x:.3,z:0},trace:[]});assert.equal(r.position.x,3.3);assert.equal(r.position.y,.12);clock=3000;r=await service.state(a.activity_token,{x:999,z:999,platform:{id:'ferry',x:.3,z:0},trace:[]});assert.equal(r.position.x,6.3);await assert.rejects(()=>service.state(a.activity_token,{x:999,z:999,platform:{id:'ferry',x:30,z:0}}));clock=5000;r=await service.state(a.activity_token,{x:11.8,z:2});assert.equal(r.position.x,11.8);assert.equal(r.position.y,0);assert.equal(r.joueurs[0].platformId,null);clock=8000;r=await service.state(a.activity_token);assert.equal(r.position.x,11.8);});
test('players can jump and attack while airborne from a moving platform',async()=>{let clock=0;const service=createActivityService({grid,now:()=>clock,resolveCharacter:async()=> 'Renne',combatEnabled:true,dungeon:{movingPlatforms:[boat]},residents:{npcs:[],disablePoms:true}}),a=await service.join({id:'a',channel:'tower'});await service.state(a.activity_token);clock=2500;let r=await service.state(a.activity_token);assert.equal(r.position.x,5);r=await service.state(a.activity_token,{x:5,z:2,action:{id:'jump',type:'jump',origin:r.position,direction:{dx:1,dz:0}}});assert.ok(r.health.jump);clock+=500;r=await service.state(a.activity_token,{x:999,z:999,action:{id:'air',type:'attack',kind:'basic',aim:{x:10,y:0,z:2}}});assert.equal(r.actionResult.error,undefined);assert.equal(r.health.canMove,true);assert.ok(r.health.jump);assert.ok(r.position.y>1.6);clock+=500;r=await service.state(a.activity_token);assert.equal(r.health.jump,null);assert.equal(r.position.x,9.5);});
test('a mobile melee strike follows the attacker at impact and permits an aerial hit',()=>{let time=1000;const room=new Map([['a',user('a')],['b',user('b','Joshua',6)]]),a=room.get('a'),b=room.get('b'),combat=createActivityCombat({grid,now:()=>time});combat.action(a,{id:'move-hit',kind:'basic',aim:{x:4,y:0,z:2}},room);a.x=4;a.y=1.65;b.y=1.65;time+=combatSpec('Renne','basic').windup;combat.tick(room);assert.equal(b.hp,88);assert.equal(a.combatLockedUntil,undefined);assert.equal(combat.snapshot().attacks[0].origin.x,4);});
test('Kloe heals herself or a living tower ally; Kevin guards himself against one hit, while regular shields absorb then expire',()=>{let time=1000;const room=new Map([['a',user('a','Kloe')],['b',user('b','Joshua',3)]]),a=room.get('a'),b=room.get('b');a.hp=40;b.hp=50;const combat=createActivityCombat({grid,now:()=>time,dungeon:{}});assert.ok(combat.action(a,{id:'heal',kind:'art',target:'b'},room).combatId);time+=1000;combat.tick(room);assert.equal(b.hp,85);assert.equal(a.hp,40);assert.equal(combat.snapshot().attacks[0].hits[0].heal,35);const pvp=createActivityCombat({grid,now:()=>time});assert.ok(pvp.action(a,{id:'enemy-heal',kind:'art',target:'b'},room).error);b.hp=0;assert.ok(combat.action(a,{id:'dead-heal',kind:'art',target:'b'},room).error);time+=1000;a.character='Kevin';const shield=createActivityCombat({grid,now:()=>time});assert.ok(shield.action(a,{id:'shield',kind:'art',target:'b'},room).combatId);time+=1000;shield.tick(room);assert.ok(a.guard);assert.equal(b.guard,undefined);assert.deepEqual(applyDamage(a,25,time),{damage:0,absorbed:25});assert.equal(a.hp,40);assert.deepEqual(applyDamage(a,25,time),{damage:25,absorbed:0});assert.equal(a.hp,15);a.shield={hp:40,until:time+100};time+=101;applyDamage(a,10,time);assert.equal(a.hp,5);assert.equal(a.shield,null);});
test('all native attack and cast animation durations and releases are twice as fast while cooldowns remain independent',()=>{for(const [name,c]of Object.entries(COMBAT))for(const [kind,raw]of Object.entries(c.actions)){const merged={...raw,...require('../activity/assets/sky/combat/hero-actions.json')[name]?.[kind]},spec=combatSpec(name,kind);assert.equal(spec.duration,merged.duration/2);assert.equal(spec.windup,merged.windup/2);assert.equal(spec.cooldown,merged.cooldown);}});
test('pink Mishy fires frequently without a warning; ordinary Mishy retains the exact warning sector as its impact',()=>{let time=1000;const p=user('a','Renne',3),room=new Map([[p.id,p]]),fire=createDungeonFire({now:()=>time}),pink=createActivityEnemies({grid:{...grid,cells:Array(1440).fill(0)},spawns:[{x:2,y:0,z:2,ranged:true}],fire,now:()=>time});pink.tick(room);assert.equal(pink.snapshot()[0].attack,null);assert.equal(fire.snapshot().length,3);time+=649;pink.tick(room);assert.equal(fire.snapshot().length,3);time++;pink.tick(room);assert.equal(fire.snapshot().length,6);const normal=createActivityEnemies({grid,spawns:[{x:2,y:0,z:2}],now:()=>time});normal.tick(room);const warning=normal.snapshot()[0].attack;time=warning.at;normal.tick(room);const impact=normal.snapshot()[0].impact;assert.equal(normal.snapshot()[0].attack,null);for(const key of ['origin','direction','angle','radius'])assert.deepEqual(impact[key],warning[key]);assert.equal(p.hp,90);});

test('all six generated ferries carry riders to their real destination across the native tower geometry',async()=>{const fs=require('node:fs'),{createActivityGeometry}=require('../utils/activityGeometry');for(let n=1;n<=3;n++){const root='activity/assets/sky/tower'+n+'/',grid=JSON.parse(fs.readFileSync(root+'navigation.json')),layout=JSON.parse(fs.readFileSync(root+'layout.json')),geometry=createActivityGeometry(JSON.parse(fs.readFileSync(root+'anterose.gltf')));assert.equal(layout.movingPlatforms.length,2);for(const boat of layout.movingPlatforms){const travel=Math.hypot(boat.to.x-boat.from.x,boat.to.z-boat.from.z)/boat.speed*1000,cycle=2*(travel+boat.dwell);let time=Math.ceil(1e12/cycle)*cycle-boat.phase;const start=time,service=createActivityService({grid,geometry,dungeon:layout,now:()=>time,spawnFor:()=>({...boat.from,y:.12}),resolveCharacter:async()=> 'Renne',combatEnabled:true,residents:{npcs:[],disablePoms:true}}),session=await service.join({id:'rider',channel:'tower'});await service.state(session.activity_token);for(time=start+100;time<start+boat.dwell+travel;time+=100){const r=await service.state(session.activity_token);assert.equal(r.health.hp,100);assert.equal(r.position.y,.12);}time=start+boat.dwell+travel;const r=await service.state(session.activity_token);assert.ok(Math.hypot(r.position.x-boat.to.x,r.position.z-boat.to.z)<.01);}}});
