const {randomBytes}=require('node:crypto');
const walk=require('../activity/liberl-walking.cjs');
const {ActivityError}=require('./activityService');
const {DT,groundField,initialAirship,validControls,stepAirship,resetAirship,startLanding}=require('../activity/airship-physics.cjs');
function createActivityAirship({config,ground,now=Date.now,resolveCharacter=async()=>'? ',onSay=()=>{},store=null,surface=ground}){
 const sessions=new Map(),players=new Map(),messages=[],ships=new Map(store?.load()?.ships??[]);let cursor=0,lastSave=-Infinity;
 function save(force=false){for(const p of players.values())ships.set(p.id,{character:p.character,mode:p.mode,foot:p.foot&&{...p.foot},airship:{...p.airship,landing:p.airship.landing&&{...p.airship.landing}}});if(store&&(force||now()-lastSave>1000)){store.save({ships:[...ships]});lastSave=now();}}
 function snapshot(p){return {id:p.id,character:p.character,...p.airship,...(p.mode==='foot'?p.foot:{}),mode:p.mode??'pilot',present:now()-p.seen<15000,hp:100,airship:{...p.airship}};}
 function prune(){for(const [id,p]of players)if(now()-p.seen>120000){ships.set(id,{character:p.character,mode:p.mode,foot:p.foot,airship:{...p.airship}});players.delete(id);}for(const [token,s]of sessions)if(s.expires<now())sessions.delete(token);}
 return {
  resetPlayer(id){players.delete(id);ships.delete(id);save(true);},refreshCharacter(){},
  async join({id,channel}){prune();let p=players.get(id);if(!p){p={id,mode:ships.get(id)?.mode??'pilot',foot:ships.get(id)?.foot,character:await resolveCharacter(id),airship:{...(ships.get(id)?.airship??initialAirship(config.spawn)),sequence:0},seen:now(),time:now(),budget:.25};players.set(id,p);}p.seen=now();const token=randomBytes(32).toString('hex');sessions.set(token,{id,channel,expires:now()+7200000});return {activity_token:token,player:snapshot(p),character:p.character,messageCursor:cursor};},
  leave(token,keep=false){const s=sessions.get(token);sessions.delete(token);if(s&&!keep){save(true);players.delete(s.id);}},
  captureMessage(message){const p=players.get(message.author);if(!p)return false;messages.push({id:'airship:'+ ++cursor,sequence:cursor,author:p.id,character:p.character,text:String(message.text).slice(0,4000),created:now()});return true;},
  async state(token,point,after=0){prune();const session=sessions.get(token),p=session&&players.get(session.id);if(!p)throw new ActivityError('Reconnectez-vous.',401);
   p.seen=now();p.budget=Math.min(2.5,p.budget+Math.max(0,(now()-p.time)/1000));p.time=now();
   const frames=point?.flight?.frames??[];if(!Array.isArray(frames)||frames.length>180)throw new ActivityError('Commande de pilotage invalide.',400);
   for(const f of frames){if(!Number.isSafeInteger(f.sequence)||!(f.mode==='foot'?walk.validWalk(f.controls):validControls(f.controls)))throw new ActivityError('Commande de pilotage invalide.',400);if(f.sequence<=p.airship.sequence)continue;if(f.sequence!==p.airship.sequence+1||p.budget<DT)break;if((f.mode??'pilot')===(p.mode??'pilot')){if(p.mode==='foot')walk.stepWalk(p.foot,f.controls,surface,[...ships.values()].map(s=>s.airship));else stepAirship(p.airship,f.controls,ground,config.spawn);}p.airship.sequence=f.sequence;p.budget-=DT;}
   let actionResult;const action=point?.action;if(action){if(typeof action.id!=='string'||action.id.length>80)throw new ActivityError('Action invalide.',400);actionResult={id:action.id};p.actionIds??=new Set();if(!p.actionIds.has(action.id)){p.actionIds.add(action.id);if(p.actionIds.size>128)p.actionIds.delete(p.actionIds.values().next().value);if(action.type==='flight_reset'){resetAirship(p.airship,config.spawn);p.mode='pilot';p.foot=null;}else if(action.type==='flight_exit'){if(p.mode==='foot')actionResult.error='Vous êtes déjà dehors.';else{const exit=walk.exitPoint(p.airship,surface);if(!exit)actionResult.error='Posez et immobilisez le Lynx près d’un sol accessible.';else{p.mode='foot';p.foot=exit;p.airship.throttle=0;save(true);}}}else if(action.type==='flight_enter'){if(p.mode!=='foot'||!walk.canBoard(p.foot,p.airship))actionResult.error='Approchez-vous de votre Lynx.';else{p.mode='pilot';p.foot=null;save(true);}}else if(action.type==='flight_land'){actionResult.error=p.mode==='foot'?'Remontez dans le Lynx.':startLanding(p.airship,ground)??undefined;}else if(action.type==='say'&&typeof action.text==='string'&&action.text.trim()&&action.text.length<=4000&&now()-(p.spoken??-Infinity)>750){p.spoken=now();this.captureMessage({author:p.id,text:action.text});if(action.rp===true)Promise.resolve().then(()=>onSay({id:'airship-say:'+action.id,actor:p.id,character:p.character,text:action.text,map:'liberl',rp:true})).catch(()=>{});}}}
   save();
   while(messages.length>50||messages[0]&&now()-messages[0].created>30000)messages.shift();
   return {character:p.character,joueurs:[...players.values()].filter(other=>other.id===p.id||other.airship.grounded||now()-other.seen<15000).map(snapshot).concat([...ships].filter(([id,s])=>!players.has(id)&&s.airship.grounded).map(([id,s])=>snapshot({id,...s,seen:-Infinity}))),mode:p.mode??'pilot',foot:p.foot&&{...p.foot},position:p.mode==='foot'?{x:p.foot.x,y:p.foot.y,z:p.foot.z}:{x:p.airship.x,y:p.airship.y,z:p.airship.z},airship:{...p.airship},movementSequence:p.airship.sequence,health:{hp:100,serverTime:now(),canMove:true},messages:messages.filter(m=>m.sequence>after),messageCursor:cursor,actionResult};
  }
 };
}
module.exports={createActivityAirship};
