const {applyDamage}=require('./activityDamage');
const {inSector}=require('../activity/dungeon-mechanics.cjs');
function inZone(p,a){if(Math.abs((p.y??0)-a.origin.y)>.95)return false;if(a.kind==='circle')return Math.hypot(p.x-a.origin.x,p.z-a.origin.z)<=a.radius;if(a.kind==='melee')return inSector(p,a);const x=p.x-a.origin.x,z=p.z-a.origin.z,along=x*a.direction.dx+z*a.direction.dz,side=x*a.direction.dz-z*a.direction.dx;return along>=0&&along<=a.length&&Math.abs(side)<=a.width/2;}
function createTowerEnemies({grid,spawns,now=Date.now,geometry=null,fire=null,initialState=null}){
 const enemies=new Map(),distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),valid=p=>{const x=Math.round((p.x-grid.origin.x)/grid.step),z=Math.round((p.z-grid.origin.z)/grid.step);return x>=0&&z>=0&&x<grid.width&&z<grid.height?grid.cells[z*grid.width+x]:null;};
 for(const [i,home]of spawns.entries()){if(!home.charger&&!home.boss)continue;const id='world:enemy:'+i,maxHp=home.boss?1500:110,saved=initialState?.enemies?.find(e=>e.id===id);enemies.set(id,{...home,id,enemy:true,character:home.boss?'MishyBoss':'TowerCharger',name:home.boss?'Sa Majesté Mishy':'Bête cuirassée',home:{...home},x:home.x,y:home.y??0,z:home.z,hp:maxHp,maxHp,heading:{dx:0,dz:-1},moving:false,speed:15,state:'idle',cooldown:now()+600,cycle:0,...(saved&&Number.isFinite(saved.hp)?{hp:Math.max(0,Math.min(maxHp,saved.hp)),deadUntil:saved.deadUntil??0}:{})});}
 const wallBetween=(a,b)=>{const d=distance(a,b),hit=geometry?.sweep({...a,y:a.y+.65},{...b,y:(b.y??0)+.65},.05);return hit&&hit.distance<d-.1;};
 function hurt(e,p,damage,time){if(wallBetween(e,p))return;applyDamage(p,damage,time);if(!p.hp)p.deadUntil=time+10000;}
 function tick(players){const time=now();for(const e of enemies.values()){
  if(e.hp<=0){e.state='dead';e.moving=false;e.attack=null;e.charge=null;if(!e.deadUntil)e.deadUntil=time+(e.boss?120000:30000);if(time>=e.deadUntil)Object.assign(e,e.home,{hp:e.maxHp,deadUntil:0,state:'idle',cooldown:time+2000});continue;}
  if(e.impact&&time>e.impact.at+700)e.impact=null;
  const targets=[...players.values()].filter(p=>p.hp>0&&!p.spectator&&distance(p,e.home)<(e.boss?22:13)&&Math.abs((p.y??0)-e.y)<3),target=targets.sort((a,b)=>distance(a,e)-distance(b,e))[0];
  if(!target){e.attack=null;e.charge=null;e.moving=false;e.state='idle';if(e.boss){e.emptySince??=time;if(time-e.emptySince>15000)e.hp=e.maxHp;}continue;}e.emptySince=null;
  if(e.charge){const a=e.charge.attack,old={x:e.x,y:e.y,z:e.z},fraction=Math.min(1,(time-e.charge.started)/e.charge.duration),desired={x:a.origin.x+a.direction.dx*a.length*fraction,y:e.y,z:a.origin.z+a.direction.dz*a.length*fraction},d=distance(old,desired),wall=geometry?.sweep({...old,y:old.y+.6},{...desired,y:desired.y+.6},.25);let f=wall&&d?Math.max(0,(wall.distance-.05)/d):1;f=Math.min(1,f);desired.x=old.x+(desired.x-old.x)*f;desired.z=old.z+(desired.z-old.z)*f;if(valid(desired)===null){desired.x=old.x;desired.z=old.z;f=0;}for(const p of targets){if(e.charge.hits.has(p.id)||Math.abs((p.y??0)-e.y)>.9)continue;const dx=desired.x-old.x,dz=desired.z-old.z,den=dx*dx+dz*dz,t=den?Math.max(0,Math.min(1,((p.x-old.x)*dx+(p.z-old.z)*dz)/den)):0;if(Math.hypot(p.x-old.x-t*dx,p.z-old.z-t*dz)<=a.width/2){hurt(e,p,22,time);e.charge.hits.add(p.id);}}Object.assign(e,desired);e.state='charge';e.moving=true;if(fraction>=1||f<1){e.charge=null;e.moving=false;e.state='recover';e.cooldown=time+1800;}continue;}
  if(e.attack){e.moving=false;e.state='attack';if(time<e.attack.at)continue;const a=e.attack;e.impact={...a,id:e.id+':'+a.started,at:time};e.attack=null;if(e.charger){e.charge={attack:a,started:time,duration:a.length/15*1000,hits:new Set()};e.state='charge';}else{for(const p of targets)if(inZone(p,a))hurt(e,p,a.damage,time);e.cooldown=time+1500;e.state='idle';}continue;}
  if(time<e.cooldown)continue;const d=distance(target,e)||1,heading={dx:(target.x-e.x)/d,dz:(target.z-e.z)/d};e.heading=heading;
  if(e.charger){let length=Math.min(9,d+1.5);for(let n=.2;n<=length;n+=.2){const p={x:e.x+heading.dx*n,y:e.y,z:e.z+heading.dz*n};if(valid(p)===null||Math.abs(valid(p)-e.y)>.35||wallBetween(e,p)){length=Math.max(0,n-.2);break;}}if(length<.6){e.cooldown=time+600;continue;}e.attack={kind:'charge',origin:{x:e.x,y:e.y,z:e.z},direction:heading,length,width:1.4,started:time,at:time+800,point:{x:target.x,y:target.y??0,z:target.z}};}
  else{const phase=e.cycle++%3;e.attack=phase===0?{kind:'circle',origin:{x:target.x,y:target.y??0,z:target.z},radius:3.6,damage:25}:{kind:phase===1?'melee':'line',origin:{x:e.x,y:e.y,z:e.z},direction:heading,radius:8,angle:Math.PI*.9,length:14,width:2.4,damage:phase===1?30:20};Object.assign(e.attack,{started:time,at:time+(phase===1?1200:1000),point:{x:target.x,y:target.y??0,z:target.z}});const words=['LES CUILLÈRES ONT DES GENOUX !','JE SUIS LE MINISTRE DES CHAUSSETTES !','MISHY A MANGÉ LE MARDI !','RENDEZ-MOI MON SOLEIL EN COMPOTE !'];e.utterance={id:e.id+':cry:'+time,text:words[(e.cycle-1)%words.length]};if(e.cycle%3===0)for(let i=0;i<12;i++)fire?.launch({x:e.x,y:e.y+.7,z:e.z},{x:Math.cos(i*Math.PI/6),y:0,z:Math.sin(i*Math.PI/6)},{speed:6.5,damage:12,ttl:2200});}e.state='attack';e.moving=false;
 }}
 return {entities:enemies,tick,snapshot:()=>[...enemies.values()].map(({home,cooldown,charge,cycle,emptySince,...e})=>({...e,heading:{...e.heading}}))};
}
module.exports={createTowerEnemies,inZone};
