import {GIFEncoder,quantize,applyPalette} from './gifenc.js';
import {NativeEffectPlayer} from './effect-player.js';
let effectPlayer,capturing=false;
const $=id=>document.getElementById(id),canvas=$('preview'),ctx=canvas.getContext('2d'),images=new Map();let catalogue,tab='sprites',selected,sequence=[],playing=true,index=0,elapsed=0,last=performance.now(),generation=0;let choices=JSON.parse(localStorage.getItem('sky-combat-choices')||'[]');
const directions=['Ouest','Nord-ouest','Nord','Nord-est','Est','Sud-est','Sud','Sud-ouest'];directions.forEach((n,i)=>$('direction').add(new Option(n,i)));
async function image(url){if(!images.has(url))images.set(url,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Image introuvable : '+url));im.src=url;}));return images.get(url);}
function status(text){$('status').textContent=text;}
function list(){const query=$('search').value.toLowerCase();$('list').replaceChildren();const entries=tab==='sprites'?Object.keys(catalogue.characters).sort().map(name=>({id:name})):tab==='effects'?catalogue.animations:catalogue.effects;for(const item of entries.filter(x=>(x.id+' '+(x.name??'')).toLowerCase().includes(query))){const b=document.createElement('button');b.classList.toggle('active',selected?.id===item.id);if(tab!=='sprites'&&item.texture){const im=document.createElement('img');im.loading='lazy';im.src=item.texture;im.alt='';b.append(im);}b.append(document.createTextNode(item.id));b.onclick=()=>select(item.id);$('list').append(b);}}
function frames(){index=0;elapsed=0;if(tab==='sprites'){const value=$('animation').value,char=catalogue.characters[selected.id];if(value.startsWith('bank:')){const bank=value.slice(5),info=char.banks[bank];sequence=Array.from({length:Math.floor(info.frames/(info.directions??8))},(_,pose)=>({bank,pose,ms:1000/+$('fps').value}));}else if(value.startsWith('current:'))sequence=char.configured.sequences[value.slice(8)].map(f=>({...f,configured:true}));else sequence=char.routines[value.slice(5)].sequence;}else if(tab==='effects'){sequence=Array.from({length:Math.ceil((effectPlayer?.duration??4000)/16.6667)},(_,frame)=>({frame,ms:16.6667}));}else{const total=+$('cols').value*+$('rows').value,first=Math.min(total-1,Math.max(0,+$('first').value||0)),length=Math.min(total-first,Math.max(0,+$('length').value||0)||total-first);sequence=Array.from({length},(_,i)=>({frame:first+i,ms:1000/+$('fps').value}));}$('frame').max=Math.max(0,sequence.length-1);$('frame').value=0;reference();}
function reference(){if(!selected)return;const text=tab==='sprites'?`${selected.id} · ${catalogue.characters[selected.id].game} · ${catalogue.characters[selected.id].source} · ${$('animation').selectedOptions[0]?.textContent} · ${directions[+$('direction').value]}`:tab==='effects'?`${selected.id} · ${(effectPlayer?.duration??0)/1000} s`:`${selected.id} · ${$('cols').value} × ${$('rows').value} · ${$('fps').value} FPS · frames ${sequence[0]?.frame??0}–${sequence.at(-1)?.frame??0} · ${$('blend').selectedOptions[0].textContent}`;$('reference').textContent=text;}
async function select(id){const stamp=++generation;selected={id};sequence=[];index=0;elapsed=0;$('title').textContent=id;$('spriteOptions').hidden=tab!=='sprites';$('effectOptions').hidden=tab==='sprites';$('atlasOptions').hidden=tab!=='textures';$('cameraOptions').hidden=tab!=='effects';$('fps').closest('label').hidden=tab==='effects';$('effectSheets').replaceChildren();$('sheet').hidden=tab==='effects';effectPlayer=null;$('animation').replaceChildren();try{if(tab==='sprites'){const char=catalogue.characters[id];$('effectCharacter').value=id;for(const [slot,r]of Object.entries(char.routines))$('animation').add(new Option(`${r.name} · AS ${slot}`,'slot:'+slot));for(const [bank,info]of Object.entries(char.banks))$('animation').add(new Option(`Banque ${bank} · ${info.source}`,'bank:'+bank));for(const key of Object.keys(char.configured?.sequences??{}))$('animation').add(new Option('Actuellement en jeu · '+key,'current:'+key));await Promise.all(Object.values(char.banks).map(info=>image(info.texture)));await Promise.all(Object.values(char.configured?.banks??{}).map(info=>image('/assets/'+info.texture)));status('Routines : poses et timings AS. Les déplacements et effets du jeu sont séparés.');}else if(tab==='effects'){selected={...catalogue.animations.find(e=>e.id===id)};if(selected.unsupported)throw Error(selected.unsupported);const player=new NativeEffectPlayer(catalogue.animations,image);await player.load(selected);if(stamp!==generation)return;effectPlayer=player;for(const info of player.root.textures.filter(Boolean)){const im=document.createElement('img');im.src=info.texture;im.alt=info.source;im.title=info.source;$('effectSheets').append(im);}status('Animation EF reconstituée · '+player.instances.length+' éléments. '+player.warnings.join(' · '));}else{selected={...catalogue.effects.find(e=>e.id===id)};await image(selected.texture);const saved=JSON.parse(localStorage.getItem('sky-effect-layout:'+id)||'null');const nativeFire=['SC/mgfire3._ds','SC/fire._ds'].includes(id);$('cols').value=saved?.columns??(nativeFire?4:1);$('rows').value=saved?.rows??(nativeFire?4:1);$('first').value=saved?.first??(id==='SC/fire._ds'?12:0);$('length').value=saved?.length??(nativeFire?4:0);$('blend').value=saved?.blend??'normal';status('Texture seule. Les assemblages animés sont dans Effets.');}if(stamp!==generation)return;frames();list();}catch(e){status(e.message);}}
function background(w,h){const kind=$('background').value;ctx.fillStyle=kind==='light'?'#d6d6d0':'#181a22';ctx.fillRect(0,0,w,h);if(kind==='check')for(let x=0;x<w;x+=24)for(let y=0;y<h;y+=24){ctx.fillStyle=((x+y)/24)%2?'#272b36':'#323744';ctx.fillRect(x,y,24,24);}}
async function draw(){const stamp=generation,f=sequence[index];if(!selected||!f)return;if(tab==='effects'){if(!effectPlayer)return;const w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}background(w,h);effectPlayer.yaw=+$('yaw').value;effectPlayer.pitch=+$('pitch').value;ctx.imageSmoothingEnabled=false;const time=index*f.ms+elapsed,count=effectPlayer.draw(ctx,time,w,h,+$('zoom').value);$('frameInfo').textContent=(time/1000).toFixed(2)+' s · '+count+' éléments';$('frame').value=index;return;}let info,im,sx,sy,fw,fh;if(tab==='sprites'){const char=catalogue.characters[selected.id];info=f.configured?char.configured.banks[f.bank]:char.banks[f.bank];if(!info)return;im=await image(f.configured?'/assets/'+info.texture:info.texture);fw=info.frameWidth;fh=info.frameHeight;const n=f.pose*(info.directions??8)+(+$('direction').value)%(info.directions??8);sx=(n%info.columns)*fw;sy=Math.floor(n/info.columns)*fh;$('sheet').src=im.src;$('frameInfo').textContent=`${index+1}/${sequence.length} · B${f.bank} pose ${f.pose} · ${f.ms} ms`;}else{im=await image(selected.texture);fw=im.width/+$('cols').value;fh=im.height/+$('rows').value;sx=(f.frame%+$('cols').value)*fw;sy=Math.floor(f.frame/+$('cols').value)*fh;$('sheet').src=im.src;$('frameInfo').textContent=`${index+1}/${sequence.length} · ${im.width} × ${im.height}`;}if(stamp!==generation)return;const w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}background(w,h);const zoom=+$('zoom').value;ctx.imageSmoothingEnabled=false;ctx.globalCompositeOperation=tab==='textures'&&$('blend').value==='add'?'lighter':'source-over';ctx.drawImage(im,sx,sy,fw,fh,(w-fw*zoom)/2,(h-fh*zoom)/2,fw*zoom,fh*zoom);ctx.globalCompositeOperation='source-over';$('frame').value=index;}
function tick(time){if(capturing){last=time;requestAnimationFrame(tick);return;}const dt=Math.min(100,time-last);last=time;if(playing&&sequence.length){elapsed+=dt*+$('speed').value;let limit=0;while(elapsed>=(sequence[index]?.ms||80)&&limit++<100){elapsed-=sequence[index]?.ms||80;index=(index+1)%sequence.length;}}void draw().catch(e=>status(e.message));requestAnimationFrame(tick);}requestAnimationFrame(tick);
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Pause':'Lecture';};function step(delta){playing=false;$('play').textContent='Lecture';index=(index+delta+sequence.length)%sequence.length;elapsed=0;} $('next').onclick=()=>step(1);$('previous').onclick=()=>step(-1);$('frame').oninput=()=>{playing=false;$('play').textContent='Lecture';index=+$('frame').value;elapsed=0;};$('animation').onchange=frames;$('direction').onchange=reference;$('fps').onchange=frames;for(const id of ['cols','rows','blend','first','length'])$(id).onchange=()=>{if(!selected)return;const cols=Math.max(1,Math.min(64,+$('cols').value||1)),rows=Math.max(1,Math.min(64,+$('rows').value||1));$('cols').value=cols;$('rows').value=rows;localStorage.setItem('sky-effect-layout:'+selected.id,JSON.stringify({columns:cols,rows,first:+$('first').value,length:+$('length').value,blend:$('blend').value}));frames();};$('search').oninput=list;
function changeTab(value){generation++;tab=value;selected=null;sequence=[];$('search').value='';$('spritesTab').classList.toggle('active',value==='sprites');$('effectsTab').classList.toggle('active',value==='effects');$('texturesTab').classList.toggle('active',value==='textures');list();const first=value==='sprites'?Object.keys(catalogue.characters)[0]:value==='effects'?(catalogue.animations.find(e=>e.id==='Third/mgfire50._ef')??catalogue.animations.find(e=>e.animation))?.id:catalogue.effects[0]?.id;if(first)void select(first);} $('spritesTab').onclick=()=>changeTab('sprites');$('effectsTab').onclick=()=>changeTab('effects');$('texturesTab').onclick=()=>changeTab('textures');
function renderSaved(){localStorage.setItem('sky-combat-choices',JSON.stringify(choices));$('saved').replaceChildren();choices.forEach((choice,i)=>{const row=document.createElement('div'),text=document.createElement('span'),remove=document.createElement('button');text.textContent=choice.reference+' · '+choice.action;remove.textContent='Retirer';remove.onclick=()=>{choices.splice(i,1);renderSaved();};row.append(text,remove);$('saved').append(row);});}
$('save').onclick=()=>{if(!selected)return;const choice={type:tab,id:selected.id,reference:$('reference').textContent,action:$('kind').value,mechanic:$('mechanic').value,notes:$('notes').value,speed:+$('speed').value,frame:index,pose:sequence[index]?.pose,bank:sequence[index]?.bank};if(tab==='sprites')Object.assign(choice,{animation:$('animation').value,direction:+$('direction').value,sequence:sequence.map(f=>({...f})),source:catalogue.characters[selected.id].source});else if(tab==='effects')Object.assign(choice,{character:$('effectCharacter').value,source:selected.source,game:selected.game,timeMs:index*(sequence[index]?.ms??0),yaw:+$('yaw').value,pitch:+$('pitch').value,preview:'EF-reconstructed',warnings:effectPlayer?.warnings??[]});else Object.assign(choice,{character:$('effectCharacter').value,source:selected.source,game:selected.game,columns:+$('cols').value,rows:+$('rows').value,first:+$('first').value,length:sequence.length,fps:+$('fps').value,blend:$('blend').value});choices.push(choice);renderSaved();status('Choix enregistré localement.');};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('reference').textContent+' · '+$('frameInfo').textContent);status('Référence copiée.');}catch{status('Sélectionne la référence ci-dessus pour la copier.');}};$('export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,choices},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='choix-combat-sky.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
fetch('/cache/catalogue.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Catalogue absent : lance la préparation.');return r.json();}).then(data=>{catalogue=data;catalogue.animations??=[];Object.keys(data.characters).sort().forEach(name=>$('effectCharacter').add(new Option(name,name)));$('count').textContent=`${Object.keys(data.characters).length} personnages · ${data.animations?.length??0} effets`;renderSaved();changeTab('sprites');}).catch(e=>status(e.message));

$('gif').onclick=async()=>{
 if(capturing||!sequence.length)return;
 const previous={index,elapsed,playing};capturing=true;playing=false;
 const controls=[...document.querySelectorAll('button,input,select,textarea')];controls.forEach(e=>e.disabled=true);
 let download;
 try{
  const encoder=GIFEncoder(),rate=15,speed=Math.max(.1,+$('speed').value);
  const duration=sequence.reduce((sum,f)=>sum+(f.ms||80),0)/speed;
  const length=Math.min(900,Math.max(1,Math.ceil(duration/1000*rate)));
  const output=document.createElement('canvas');output.width=640;output.height=Math.round(640*canvas.clientHeight/canvas.clientWidth);
  const out=output.getContext('2d');out.imageSmoothingEnabled=false;
  for(let frame=0;frame<length;frame++){
   let time=frame*1000/rate*speed;index=0;
   while(index<sequence.length-1&&time>=(sequence[index].ms||80)){time-=sequence[index].ms||80;index++;}
   elapsed=time;await draw();out.drawImage(canvas,0,0,output.width,output.height);
   const rgba=out.getImageData(0,0,output.width,output.height).data,palette=quantize(rgba,256);
   encoder.writeFrame(applyPalette(rgba,palette),output.width,output.height,{palette,delay:Math.round(1000/rate),repeat:0});
   status(`GIF : ${frame+1}/${length}`);
   if(frame%3===0)await new Promise(resolve=>setTimeout(resolve,0));
  }
  encoder.finish();const blob=new Blob([encoder.bytes()],{type:'image/gif'});
  download=URL.createObjectURL(blob);
  const response=await fetch('/copy-gif',{method:'POST',headers:{'Content-Type':'image/gif'},body:blob});
  const result=await response.json();if(!response.ok||!result.copied)throw Error(result.error||'Copie indisponible');
  status('GIF copié. Colle-le dans Discord avec Ctrl+V.'+(duration>60000?' Extrait limité à 60 secondes.':''));
 }catch(error){status('Copie indisponible : '+error.message);if(download){const a=document.createElement('a');a.href=download;a.download='animation-sky.gif';a.textContent='Télécharger le GIF';$('status').append(' ',a);}}
 finally{if(download)setTimeout(()=>URL.revokeObjectURL(download),300000);index=previous.index;elapsed=previous.elapsed;playing=previous.playing;capturing=false;controls.forEach(e=>e.disabled=false);}
};
