import assert from 'node:assert/strict';
import {NativeEffectPlayer,sampleKeys} from './effect-player.js';
assert.deepEqual(sampleKeys([{time:0,value:[0,0,0]},{time:400,value:[0,4,0]}],100,[]),[0,1,0]);
const base={enabled:true,renderFlags:4,textureIndex:0,duration:1000,motion:0,position:[],rotation:[],scale:[],color:[],emissions:[]};
const child={...base,index:1,duration:200};
const root={...base,index:0,emissions:[{kind:0,part:1,repeat:3,count:1,delay:150,interval:200,variation:0,trigger:0}]};
const effect={id:'fixture',parts:[root,child],textures:[null]};
const player=new NativeEffectPlayer([],async()=>null);player.duration=1000;
player.schedule(effect,0,0,[0,0,0],null,0,1,[]);
assert.deepEqual(player.instances.map(p=>p.start),[0,150,350,550]);
assert.equal(player.state(player.instances[1],149),null);
assert.notEqual(player.state(player.instances[1],150),null);
assert.equal(player.state(player.instances[1],351),null);
root.emissions[0].repeat=254;player.instances=[];
player.schedule(effect,0,0,[0,0,0],null,0,1,[]);
assert.equal(player.instances.length,2,'254 means one fixed preview target, not 254 repeated explosions');
root.emissions[0].trigger=2;player.instances=[];
player.schedule(effect,0,0,[0,0,0],null,0,1,[]);
assert.equal(player.instances[1].start,1000,'end-triggered child starts at parent termination');
root.emissions[0].kind=1;root.emissions[0].part=0;effect.children=['hit.eff'];effect.game='SC';
const hit={id:'SC/hit._ef',parts:[child],textures:[null]};player.definitions=new Map([[hit.id,hit]]);player.instances=[];
player.schedule(effect,0,0,[0,0,0],null,0,1,[]);
assert.equal(player.instances.length,2,'linked EF is scheduled instead of recursively replaying the root');
console.log('Playback: interpolation, emission timings, lifetimes, target count and linked effect OK');

const delayedRoot={...base,index:0,duration:10,emissions:[{kind:0,part:1,repeat:1,count:1,delay:200,interval:0,variation:0,trigger:0}]};
player.instances=[];player.duration=4000;player.schedule({...effect,parts:[delayedRoot,child]},0,0,[0,0,0],null,0,1,[]);
assert.equal(player.instances[1].start,200,'delayed shield emission survives a short-lived root controller');
const blue={...base,color:[{time:0,value:0x0000ffff}]};player.instances=[];player.schedule({...effect,parts:[blue]},0,0,[0,0,0],null,0,1,[]);
assert.deepEqual(player.state(player.instances[0],0).color,[0,0,255,255],'packed native blue must not become red');
console.log('Delayed controllers and native RGBA colours OK');

const cylinderPart={vertices:[[.8,1,0],[.6,-1,0]],uv:[.25,0,.5,.25],renderFlags:4};
let cylinder;
player.drawModel=(_ctx,model)=>{cylinder=model.meshes[0];return 1;};
player.drawCylinder({}, {part:cylinderPart,texture:{}}, {}, 100,100,1);
assert.equal(cylinder.positions.length,66);
assert.ok(cylinder.positions.every(p=>p.every(Number.isFinite)));
assert.deepEqual(cylinder.positions[0], [.8,1,0]);
assert.equal(cylinder.uv[0][0],.25);assert.equal(cylinder.uv.at(-1)[0],.5);
assert.ok(Math.abs(cylinder.positions[0][0]-cylinder.positions.at(-2)[0])<1e-6);
console.log('Native casting cylinder: closed geometry and atlas UVs OK');
