import walking from './liberl-walking.cjs';
import surfaces from './walking-surface.cjs';
import {createLiberlAvatars} from './liberl-avatars.mjs';
import {createCombatControls} from './combat-controls.mjs';
import {createArenaCutaway} from './scene-visibility.mjs';
import {createDayNight} from './day-night.mjs';
import {createAirshipExplosions} from './airship-explosion.mjs';
import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {loadLynx} from './lynx-model.mjs';
import {preloadAssets} from './asset-preload.mjs';
import {createRooftopSky,PANORAMA_FILES} from './rooftop-sky.mjs';
import physics from './airship-physics.cjs';
import {createDialogues} from './dialogue.mjs';
import {keyboardLayout,CAMERA_PITCH,CAMERA_ZOOM} from './controls.mjs';
export async function createAirshipScene(canvas,assets){
 const scene=new THREE.Scene(),renderer=new THREE.WebGLRenderer({canvas,antialias:true}),camera=new THREE.PerspectiveCamera(55,1,.2,12000);
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0x4b667e);renderer.outputColorSpace=THREE.SRGBColorSpace;
 const folder=new URL('liberl/',assets),config=await fetch(new URL('airship.json',folder),{cache:'no-store'}).then(r=>r.json()),layout=await fetch(new URL('layout.json',folder),{cache:'no-store'}).then(r=>r.json());
 const versioned=url=>{const u=new URL(url,folder);u.searchParams.set('v',layout.revision);return u.href;};
 const terrain=await fetch(versioned('terrain.gltf')).then(r=>r.json()),meta=await fetch(versioned('flight-ground.json')).then(r=>r.json()),groundBytes=await fetch(versioned('flight-ground.bin')).then(r=>r.arrayBuffer()),ground=physics.groundField(meta,new Float32Array(groundBytes));
 const loading=document.createElement('div');loading.style.cssText='position:fixed;inset:0;display:grid;place-items:center;background:#201b18e8;color:#ffe7b0;z-index:40;font:20px system-ui';loading.textContent='Chargement du Liberl…';document.body.append(loading);
 const skyAssets=new URL('tower4/',assets),manager=new THREE.LoadingManager();let cached;
 try{cached=await preloadAssets(terrain.buffers.filter(b=>!b.uri.startsWith('data:')).map(b=>versioned(b.uri)).concat(PANORAMA_FILES.map(f=>versioned(new URL(f,skyAssets).href))),{onProgress:(n,total)=>loading.textContent=`Chargement ${n}/${total}`});
 manager.setURLModifier(url=>url.startsWith('blob:')||url.startsWith('data:')?url:cached.resolve(versioned(url)));
 const model=(await new GLTFLoader(manager).loadAsync(new URL('terrain.gltf',folder).href)).scene;scene.add(model);
 const sky=await createRooftopSky(THREE,scene,skyAssets,manager);cached.dispose();cached=null;
 const ship=await loadLynx(THREE,assets,config.length);scene.add(ship);
 model.traverse(o=>{if(o.isMesh)for(const m of [].concat(o.material)){if(m.map){m.map.magFilter=THREE.NearestFilter;m.map.minFilter=THREE.LinearMipmapLinearFilter;}m.polygonOffset=true;m.polygonOffsetFactor=.1;}});
 loading.remove();return finish({scene,renderer,camera,ship,sky,config,ground,canvas,assets,layout,model});
 }catch(error){cached?.dispose();loading.remove();renderer.dispose();throw error;}
}
async function finish({scene,renderer,camera,ship,sky,config,ground,canvas,assets,layout,model}){
 const navigationLights=[{position:[0,0,0],color:[1,.1,.1],radius:5,strength:.8},{position:[0,0,0],color:[.1,1,.3],radius:5,strength:.8}];const dayNight=createDayNight(THREE,model,'liberl',null,navigationLights);dayNight.apply(ship);const explosions=await createAirshipExplosions(THREE,scene,assets);
 const surface=surfaces.createWalkingSurface(THREE,model),walkers=await createLiberlAvatars(THREE,scene,assets,dayNight),walkControls=createCombatControls(()=>{}),pilotCamera=camera,footCamera=new THREE.OrthographicCamera(-8,8,8,-8,.1,12000),cutaway=createArenaCutaway();
 model.traverse(o=>{if(o.isMesh)for(const material of [].concat(o.material)){material.clippingPlanes=cutaway.planes;material.clipIntersection=true;material.needsUpdate=true;}});
 const {DT,stepAirship,initialAirship}=physics,keys=new Set(),remote=new Map(),dialogues=await createDialogues(assets);
 let mode='pilot',foot=null,walkTarget=null;
 let state=initialAirship(config.spawn),localId=null,character='?',connected=false,disposed=false,sequence=0,frames=[],actions=[],notify=()=>{},last=performance.now(),accumulator=0,orbit=0,pitchOrbit=.7,drag=null,noticeUntil=0,takeoffAssist=false;
 const avatars=new Map(),panel=document.createElement('div');panel.id='sky-airship';panel.style.cssText='position:fixed;left:12px;bottom:100px;z-index:24;background:#211c2ae8;color:#ffe7b0;border:1px solid #b49760;border-radius:5px;padding:10px;font:15px AveriaSky,system-ui;max-width:260px';
 const stats=document.createElement('div'),label=document.createElement('label'),throttle=document.createElement('input');throttle.type='range';throttle.min=0;throttle.max=100;throttle.value=0;label.textContent='Gaz ';label.append(throttle);label.style.display='block';
 const takeoff=document.createElement('button');takeoff.textContent='Décoller';takeoff.onclick=()=>{throttle.value='100';takeoffAssist=true;};
 const land=document.createElement('button');land.textContent='Atterrir';land.onclick=()=>{queue('flight_land');throttle.value='0';takeoffAssist=false;};
 const exit=document.createElement('button');exit.textContent='Sortir';exit.onclick=()=>queue(mode==='foot'?'flight_enter':'flight_exit');
 const reset=document.createElement('button');reset.textContent='Retour piste';reset.onclick=()=>queue('flight_reset');
 const help=document.createElement('details'),title=document.createElement('summary');title.textContent='Commandes';help.append(title,document.createTextNode('↑/↓ : cabrer/piquer · ←/→ : incliner · Maj/Ctrl : gaz. ZQSD ou WASD aussi. Clic droit : caméra.'));
 const touch=document.createElement('div');touch.style.cssText='display:flex;gap:5px;margin-top:8px';const held={pitch:0,roll:0};
 for(const [text,axis,value]of [['←','roll',-1],['↑','pitch',1],['↓','pitch',-1],['→','roll',1]]){const b=document.createElement('button');b.textContent=text;b.style.cssText='min-width:42px;min-height:42px;touch-action:none';b.onpointerdown=e=>{held[axis]=value;b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>held[axis]=0;touch.append(b);}
 const touchStyle=document.createElement('style');touchStyle.textContent='#sky-airship [hidden]{display:none!important}#sky-airship[data-mode=foot]{bottom:240px}#sky-airship button{background:#f3dfb4;color:#332319;border:0;border-radius:3px;padding:6px;margin:3px;cursor:pointer}#sky-airship details{font:12px system-ui;max-width:250px;margin-top:6px}#sky-airship label{display:flex;align-items:center}#sky-airship input{max-width:170px}#sky-airship[data-connected=false]{opacity:.6}#sky-airship>div:last-child{display:none}@media(any-pointer:coarse),(max-width:600px){#sky-airship{bottom:14px;left:8px;padding:6px;max-width:235px;font-size:13px}#sky-airship>div:last-child{display:flex!important}#sky-airship details{display:none}}';
 panel.append(stats,label,takeoff,land,exit,reset,help,touch);document.body.append(panel);document.head.append(touchStyle);
 function queue(type,text,rp){if(__ACTIVITY_PREVIEW__&&!new URLSearchParams(location.search).has('frame_id')&&type==='flight_land'){const error=physics.startLanding(state,ground);if(error){stats.textContent=error;noticeUntil=performance.now()+3000;}else throttle.value='0';return true;}if(__ACTIVITY_PREVIEW__&&!new URLSearchParams(location.search).has('frame_id')&&type==='flight_reset'){physics.resetAirship(state,config.spawn);throttle.value='0';takeoffAssist=false;return true;}const action={id:crypto.randomUUID(),type,text,rp};if(actions.length<16){actions.push(action);notify();return true;}return false;}
 function controls(){if(mode==='foot'){const azerty=keyboardLayout()==='AZERTY',stick=walkControls.vector(),horizontal=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has(azerty?'q':'a')?1:0)+stick.x,vertical=(keys.has('ArrowUp')||keys.has(azerty?'z':'w')?1:0)-(keys.has('ArrowDown')||keys.has('s')?1:0)-stick.y;const right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0),forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;forward.normalize();let dx=right.x*horizontal+forward.x*vertical,dz=right.z*horizontal+forward.z*vertical;if(horizontal||vertical)walkTarget=null;else if(walkTarget){dx=walkTarget.x-foot.x;dz=walkTarget.z-foot.z;if(Math.hypot(dx,dz)<.12){walkTarget=null;dx=dz=0;}}const length=Math.max(1,Math.hypot(dx,dz));return {dx:dx/length,dz:dz/length};}const azerty=keyboardLayout()==='AZERTY',up=azerty?'z':'w',left=azerty?'q':'a';if(keys.has('ShiftLeft')||keys.has('ShiftRight'))throttle.value=String(Math.min(100,+throttle.value+30*DT));if(keys.has('ControlLeft')||keys.has('ControlRight'))throttle.value=String(Math.max(0,+throttle.value-30*DT));if(!state.grounded)takeoffAssist=false;return {pitch:held.pitch||((keys.has('ArrowUp')||keys.has(up)?1:0)-(keys.has('ArrowDown')||keys.has('s')?1:0))||(takeoffAssist&&state.pitch<.4?1:0),roll:held.roll||((keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has(left)?1:0)),throttle:+throttle.value/100};}
 function keydown(e){if(mode==='foot'&&e.code==='Space'){if(!e.target.closest?.('input,textarea,select,[contenteditable]')){e.preventDefault();if(!e.repeat&&walking.canBoard(foot,state))queue('flight_enter');}return;}if(e.target.closest?.('input,textarea,select,[contenteditable]'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ControlLeft','ControlRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);keys.add(e.key.toLowerCase());}
 function keyup(e){keys.delete(e.code);keys.delete(e.key.toLowerCase());}function blur(){keys.clear();held.pitch=held.roll=0;drag=null;}
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();function aim(e){pointer.set(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2);ray.setFromCamera(pointer,camera);return ray;}
 function down(e){if(e.pointerType==='touch')document.body.setAttribute('data-sky-touch','');if(mode==='foot'&&e.button===0&&e.pointerType!=='touch'){const hit=aim(e).intersectObject(model,true).find(h=>Math.abs(h.face.normal.clone().transformDirection(h.object.matrixWorld).y)>.65);if(hit)walkTarget={x:hit.point.x,z:hit.point.z};return;}if(e.button===2||e.pointerType==='touch'){drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);}}
 function move(e){if(!drag||drag.id!==e.pointerId)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>3)drag.moved=true;orbit+=(e.clientX-drag.x)*.006;pitchOrbit=Math.max(-.15,Math.min(1.1,pitchOrbit-(e.clientY-drag.y)*.006));drag.x=e.clientX;drag.y=e.clientY;}
 function up(e){if(mode==='foot'&&drag&&!drag.moved){const r=aim(e);if(r.intersectObject(ship,true).length&&walking.canBoard(foot,state))queue('flight_enter');else if(e.pointerType==='touch'){const hit=r.intersectObject(model,true).find(h=>Math.abs(h.face.normal.clone().transformDirection(h.object.matrixWorld).y)>.65);if(hit)walkTarget={x:hit.point.x,z:hit.point.z};}}drag=null;}function context(e){e.preventDefault();}
 function resize(){renderer.setSize(innerWidth,innerHeight,false);pilotCamera.aspect=innerWidth/innerHeight;pilotCamera.updateProjectionMatrix();const aspect=innerWidth/innerHeight;footCamera.left=-CAMERA_ZOOM*aspect;footCamera.right=CAMERA_ZOOM*aspect;footCamera.top=CAMERA_ZOOM;footCamera.bottom=-CAMERA_ZOOM;footCamera.updateProjectionMatrix();}
 for(const [event,handler]of [['keydown',keydown],['keyup',keyup],['blur',blur],['resize',resize]])addEventListener(event,handler);
 for(const [event,handler]of [['pointerdown',down],['pointermove',move],['pointerup',up],['pointercancel',up],['contextmenu',context]])canvas.addEventListener(event,handler);resize();
 const target=new THREE.Vector3();camera.position.set(state.x,state.y+40,state.z+25);
 function place(model,s){model.position.set(s.x,s.y,s.z);model.rotation.set(s.pitch,s.yaw,s.roll,'YXZ');}
 function frame(time){if(disposed)return;const delta=Math.min(.1,(time-last)/1000);last=time;accumulator+=delta;
  while(accumulator>=DT){accumulator-=DT;if(connected&&frames.length<180){const input=controls(),before=state.crashes;if(mode==='foot')walking.stepWalk(foot,input,surface,[state,...[...remote.values()].map(r=>r.target)]);else stepAirship(state,input,ground,config.spawn);frames.push({sequence:++sequence,mode,controls:input});state.sequence=sequence;if(state.crashes>before){throttle.value='0';takeoffAssist=false;stats.textContent='Impact · retour sur la piste';noticeUntil=time+2500;}if(__ACTIVITY_PREVIEW__&&!new URLSearchParams(location.search).has('frame_id'))frames=[];}}
  explosions.observe(localId??'local',state);explosions.update(delta);ship.visible=!state.crashRemaining;place(ship,state);const speed=Math.hypot(state.vx,state.vz),angle=state.yaw+orbit,distance=24;
  if(mode==='foot'){const distance=120;target.set(foot.x+Math.sin(orbit)*distance*Math.cos(CAMERA_PITCH),foot.y+Math.sin(CAMERA_PITCH)*distance,foot.z+Math.cos(orbit)*distance*Math.cos(CAMERA_PITCH));camera.position.copy(target);camera.lookAt(foot.x,foot.y+.6,foot.z);}else{target.set(state.x+Math.sin(angle)*distance*Math.cos(pitchOrbit),Math.max(state.y+6+Math.sin(pitchOrbit)*distance,(ground.floor(state.x,state.z)??state.y-40)+38),state.z+Math.cos(angle)*distance*Math.cos(pitchOrbit));camera.position.lerp(target,1-Math.exp(-delta*5));camera.lookAt(state.x,state.y+3,state.z);}camera.updateMatrixWorld();renderer.localClippingEnabled=mode==='foot';if(mode==='foot')cutaway.update(camera,new THREE.Vector3(foot.x,foot.y,foot.z));
  if(localId){const a=walkers.avatars.get(localId);if(a)a.position=foot;avatars.set(localId,mode==='foot'&&a?a:{mesh:ship,character,position:state,height:5,info:{height:5}});}
  for(const [id,r]of remote){explosions.observe(id,r.target);r.model.visible=!r.target.crashRemaining;r.model.position.lerp(new THREE.Vector3(r.target.x,r.target.y,r.target.z),1-Math.exp(-delta*10));r.model.quaternion.slerp(new THREE.Quaternion().setFromEuler(new THREE.Euler(r.target.pitch,r.target.yaw,r.target.roll,'YXZ')),1-Math.exp(-delta*10));}
  if(time>noticeUntil){const location=mode==='foot'?foot:state,nearest=layout.regions.reduce((a,b)=>Math.hypot(a.center[0]-location.x,a.center[2]-location.z)<Math.hypot(b.center[0]-location.x,b.center[2]-location.z)?a:b);stats.textContent=mode==='foot'?`À pied · ${nearest.name}`:`Lynx · ${Math.round(speed)} u/s · ${Math.round(state.y-(ground.floor(state.x,state.z)??ground.meta.minY))} m\n${state.landing?'Atterrissage':state.grounded?'Au sol':speed<physics.STALL_SPEED?'Décrochage':'En vol'} · ${nearest.name}`;}
  panel.dataset.mode=mode;for(const node of [label,takeoff,land,reset,help,touch])node.hidden=mode==='foot';exit.textContent=mode==='foot'?'Remonter':'Sortir';exit.disabled=mode==='foot'?!walking.canBoard(foot,state):!state.grounded||!!state.landing||!!state.crashRemaining||Math.hypot(state.vx,state.vz)>1;walkControls.update({arena:false,character,connected:connected&&mode==='foot',alive:true,spectator:false,health:{},visible:mode==='foot'});walkers.update(time,camera);land.disabled=state.grounded||!!state.landing||!!state.crashRemaining;takeoff.disabled=!state.grounded||!!state.landing||!!state.crashRemaining;ship.updateMatrixWorld(true);navigationLights.forEach((source,i)=>source.position=ship.localToWorld(new THREE.Vector3(i?3.6:-3.6,1.3,0)).toArray());const light=dayNight.update();renderer.setClearColor(new THREE.Color(.3*light.tint[0],.4*light.tint[1],.5*light.tint[2]));sky.update(camera,light);dialogues.update(time,avatars,camera);renderer.render(scene,camera);requestAnimationFrame(frame);
 }
 requestAnimationFrame(frame);
 return {spawn:config.spawn,catalogue:{},onAction(fn){notify=fn;},onTerminal(){},onCraftCapture(){},setConnected(value){connected=value;panel.dataset.connected=String(value);if(!value)blur();document.body.toggleAttribute('data-sky-touch',matchMedia('(any-pointer:coarse)').matches);},
  async me(player){localId=player.id;character=player.character;mode=player.mode??'pilot';foot=player.mode==='foot'?{x:player.x,y:player.y,z:player.z,heading:player.heading}:null;camera=mode==='foot'?footCamera:pilotCamera;if(foot)await walkers.set(localId,character,foot);state={...(player.airship??initialAirship(config.spawn))};sequence=state.sequence;throttle.value=String(state.throttle*100);},
  async resetSession(player){frames=[];actions=[];await this.me(player);},
  position:()=>mode==='foot'?{x:foot.x,y:foot.y,z:foot.z}:{x:state.x,y:state.y,z:state.z},movement:()=>({flight:{frames:frames.map(f=>({...f,controls:{...f.controls}}))},sequence}),acknowledgeMovement(){},correct(){},
  async world(result){dayNight.sync(result.health?.serverTime);if(result.airship){const nextMode=result.mode??'pilot';if(nextMode!==mode){mode=nextMode;frames=[];sequence=result.airship.sequence;walkTarget=null;blur();camera=mode==='foot'?footCamera:pilotCamera;}foot=result.foot&&{...result.foot};if(mode==='foot')await walkers.set(localId,character,foot);else walkers.remove(localId);const ack=result.airship.sequence,oldCrash=state.crashes;frames=frames.filter(f=>f.sequence>ack);state={...result.airship};for(const f of frames){if(f.mode===mode){if(mode==='foot')walking.stepWalk(foot,f.controls,surface,[state,...[...remote.values()].map(r=>r.target)]);else stepAirship(state,f.controls,ground,config.spawn);}state.sequence=f.sequence;}sequence=Math.max(sequence,ack);if(state.crashes>oldCrash){throttle.value='0';frames=[];sequence=ack;stats.textContent='Impact · retour sur la piste';noticeUntil=performance.now()+2500;}}
   if(actions[0]&&result.actionResult?.id===actions[0].id){const action=actions.shift();if(action.type==='flight_land'&&!result.actionResult.error){throttle.value='0';takeoffAssist=false;}if(action.type==='flight_reset'){state={...result.airship};frames=[];sequence=state.sequence;throttle.value='0';takeoffAssist=false;}if(result.actionResult.error){stats.textContent=result.actionResult.error;noticeUntil=performance.now()+3000;}}
  },
  async sync(players){const present=new Set();for(const p of players){if(p.id===localId||!p.airship)continue;present.add(p.id);let r=remote.get(p.id);if(!r){const model=ship.clone(true);scene.add(model);r={model,target:p.airship};place(model,p.airship);remote.set(p.id,r);}r.target=p.airship;if(p.mode==='foot'&&p.present!==false){const a=await walkers.set(p.id,p.character,{x:p.x,y:p.y,z:p.z,heading:p.heading,walking:p.walking});avatars.set(p.id,a);}else{walkers.remove(p.id);avatars.set(p.id,{mesh:r.model,character:p.character,position:r.target,height:5,info:{height:5}});}}for(const [id,r]of remote)if(!present.has(id)){scene.remove(r.model);remote.delete(id);avatars.delete(id);walkers.remove(id);}},
  messages:m=>dialogues.receive(m),speak:(text,rp)=>connected&&text.trim()?queue('say',text.trim(),rp):false,action:()=>actions[0],leaveDuel:()=>queue('leave_map'),captureNotice(text){stats.textContent=text;noticeUntil=performance.now()+3000;},
  ...(__ACTIVITY_PREVIEW__?{setDayTime:time=>dayNight.setTime(time),dayTime:()=>dayNight.state(),airshipState:()=>({...state}),setThrottle:value=>throttle.value=String(value*100),startFlight:()=>{throttle.value='100';takeoffAssist=true;},renderInfo:()=>({perspective:camera.isPerspectiveCamera===true,mode,calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,camera:camera.position.toArray()})}:{}),
  dispose(){disposed=true;blur();for(const [event,handler]of [['keydown',keydown],['keyup',keyup],['blur',blur],['resize',resize]])removeEventListener(event,handler);for(const [event,handler]of [['pointerdown',down],['pointermove',move],['pointerup',up],['pointercancel',up],['contextmenu',context]])canvas.removeEventListener(event,handler);panel.remove();touchStyle.remove();dialogues.dispose();walkControls.dispose();walkers.dispose();sky.dispose();dayNight.dispose();explosions.dispose();const materials=new Set(),textures=new Set();scene.traverse(o=>{o.geometry?.dispose();for(const m of [].concat(o.material??[])){materials.add(m);if(m.map)textures.add(m.map);}});for(const t of textures)t.dispose();for(const m of materials)m.dispose();renderer.dispose();}
 };
}
