import mechanics from './dungeon-mechanics.cjs';
// Native FIRE animation is shared by torches and dodgeable projectiles.
export async function createDungeonEffects(THREE,scene,assets,layout){
 const texture=await new THREE.TextureLoader().loadAsync(new URL('effects/fire-frames.png',assets).href);texture.colorSpace=THREE.SRGBColorSpace;
 const fires=new Map(),decorations=[],flames=[];
 function flame(){const map=texture.clone();map.repeat.set(.25,1);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));scene.add(sprite);return sprite;}
 for(const source of layout.torches??[]){const [x,y,z]=source.position;const pole=new THREE.Mesh(new THREE.CylinderGeometry(.07,.1,y-.2,6),new THREE.MeshBasicMaterial({color:0x5c3921}));pole.position.set(x,(y-.2)/2,z);scene.add(pole);decorations.push(pole);const bowl=new THREE.Mesh(new THREE.CylinderGeometry(.23,.12,.22,8),new THREE.MeshBasicMaterial({color:0x846447}));bowl.position.set(x,y-.2,z);scene.add(bowl);decorations.push(bowl);const f=flame();f.position.set(x,y+.18,z);f.scale.set(.65,.95,1);flames.push(f);}
 for(const t of layout.traps??[]){const emitter=flame();emitter.position.set(t.start.x,t.start.y+t.height,t.start.z);emitter.scale.set(.45,.45,1);emitter.userData.height=.45;flames.push(emitter);}
 let shots=[],clock=Date.now(),received=performance.now();
 return {receive(items,time){shots=items;clock=time;received=performance.now();},update(){const now=clock+performance.now()-received,seen=new Set();for(const shot of shots){if(now>shot.started+shot.ttl)continue;seen.add(shot.id);let item=fires.get(shot.id);if(!item){item=flame();item.scale.set(.65,.65,1);fires.set(shot.id,item);}const p=mechanics.projectilePoint(shot,now);item.position.set(p.x,p.y,p.z);item.material.map.offset.x=Math.floor(now/65)%4/4;}for(const[id,item]of fires)if(!seen.has(id)){scene.remove(item);item.material.map.dispose();item.material.dispose();fires.delete(id);}flames.forEach((f,i)=>{f.material.map.offset.x=(Math.floor(now/75)+i)%4/4;f.scale.y=(f.userData.height??.95)+.1*Math.sin(now*.017+i);});},dispose(){for(const item of [...fires.values(),...flames]){scene.remove(item);item.material.map.dispose();item.material.dispose();}for(const item of decorations){scene.remove(item);item.geometry.dispose();item.material.dispose();}fires.clear();texture.dispose();}};
}
