import {facing} from './movement.mjs';
import native from './native-combat.cjs';
export async function createLiberlAvatars(THREE,scene,assets,dayNight){
 const catalogue=await fetch(new URL('characters.json',assets)).then(r=>r.json()),avatars=new Map(),textures=new Map(),loader=new THREE.TextureLoader(),labels=document.createElement('div');labels.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:10';document.body.append(labels);
 async function texture(info){if(!textures.has(info.texture))textures.set(info.texture,loader.loadAsync(new URL(info.texture,assets).href));const map=(await textures.get(info.texture)).clone();map.colorSpace=THREE.SRGBColorSpace;map.magFilter=map.minFilter=THREE.NearestFilter;map.generateMipmaps=false;map.repeat.set(1/info.columns,1/info.rows);return map;}
 function remove(id){const a=avatars.get(id);if(!a)return;scene.remove(a.mesh);a.label.remove();a.mesh.geometry.dispose();a.mesh.material.dispose();a.idle.dispose();if(a.run!==a.idle)a.run.dispose();avatars.delete(id);}
 return {avatars,async set(id,character,position){let a=avatars.get(id);if(a?.character===character){a.position=position;return a;}remove(id);const info=catalogue[character]??native.COMBAT[character]?.banks['0']??catalogue.Estelle,walking=info.walk??native.COMBAT[character]?.banks['1']??info,idle=await texture(info),run=walking===info?idle:await texture(walking),height=info.height;
  const geometry=new THREE.PlaneGeometry(height*info.frameWidth/info.frameHeight,height);geometry.translate(info.centerX??0,info.centerY??height/2,0);const mesh=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({map:idle,transparent:true,alphaTest:.15,depthWrite:true,side:THREE.DoubleSide}));scene.add(mesh);dayNight.apply(mesh);const label=document.createElement('div');label.textContent=character;label.style.cssText='position:absolute;transform:translate(-50%,-100%);font:bold 14px AveriaSky,system-ui;color:#ffe7b0;background:#211c2acc;padding:2px 5px;border-bottom:3px solid #8bcc65';labels.append(label);a={mesh,label,character,position,info,height,idle,run,walking};avatars.set(id,a);return a;
 },remove,update(time,camera){const right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0),forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;forward.normalize();for(const a of avatars.values()){const p=a.position,info=p.walking?a.walking:a.info,direction=facing(p.heading?.dx??0,p.heading?.dz??-1,right,forward),poses=p.walking?info.run??[0,1,2,3]:info.idle??[0],pose=poses[Math.floor(time/1000*(info.fps??12))%poses.length],frame=pose*(info.directions??8)+direction,map=p.walking?a.run:a.idle;a.mesh.material.map=map;map.offset.set((frame%info.columns)/info.columns,1-(Math.floor(frame/info.columns)+1)/info.rows);a.mesh.position.set(p.x,p.y-(a.info.footOffsets?.[direction]??0),p.z);a.mesh.rotation.y=Math.atan2(camera.matrixWorld.elements[8],camera.matrixWorld.elements[10]);const screen=new THREE.Vector3(p.x,p.y+a.height+.2,p.z).project(camera);a.label.hidden=Math.abs(screen.x)>1.1||Math.abs(screen.y)>1.1||Math.abs(screen.z)>1;a.label.style.left=(screen.x+1)*innerWidth/2+'px';a.label.style.top=(1-screen.y)*innerHeight/2+'px';}},dispose(){for(const id of [...avatars.keys()])remove(id);for(const promise of textures.values())promise.then(t=>t.dispose());textures.clear();labels.remove();}};
}
