export function createTerminalUI({menu,action,changed}) {
 const panel=document.createElement("dialog"),heading=document.createElement("h2"),content=document.createElement("div"),error=document.createElement("p");
 panel.id="sky-terminal";panel.setAttribute("aria-label","Capel");heading.textContent="Capel";error.setAttribute("role","status");
 const close=document.createElement("button");close.type="button";close.textContent="\u00d7";close.setAttribute("aria-label","Fermer");close.className="sky-terminal-close";close.onclick=()=>panel.close();
 panel.append(close,heading,content,error);document.body.append(panel);
 const invitations=document.createElement("div");invitations.id="sky-invitations";invitations.hidden=true;invitations.setAttribute("role","status");document.body.append(invitations);
 const style=document.createElement("style");style.textContent=`#sky-terminal{box-sizing:border-box;width:360px;max-width:calc(100vw - 24px);max-height:calc(100dvh - 80px);overflow:auto;background:#211c2af5;color:#ffe7b0;border:2px solid #b49760;border-radius:6px;padding:20px;font:18px AveriaSky,sans-serif}#sky-terminal::backdrop{background:#0008}#sky-terminal h2{margin:0 0 18px;font-size:25px}#sky-terminal h3{font-size:19px;margin:18px 0 8px}#sky-terminal button,#sky-terminal select,#sky-invitations button,#sky-prophunt button{font:inherit;background:#ead29c;color:#241b15;border:1px solid #b49760;border-radius:4px;padding:9px;cursor:pointer;min-height:44px}#sky-terminal select{width:100%;margin-bottom:8px}#sky-terminal button:disabled,#sky-invitations button:disabled{opacity:.5;cursor:wait}#sky-terminal .sky-terminal-close{position:absolute;right:6px;top:6px;background:transparent;color:#ffe7b0;border:0;font-size:24px}#sky-terminal p:empty{display:none}#sky-terminal p{font-size:15px;margin-bottom:0}#sky-invitations{position:fixed;left:50%;transform:translateX(-50%);bottom:16px;z-index:40;padding:12px;background:#211c2af5;color:#ffe7b0;border:2px solid #b49760;border-radius:6px;font:17px AveriaSky,sans-serif;max-width:calc(100vw - 48px)}#sky-invitations button{margin:8px 6px 0 0}#sky-invitations p{margin:0}`;document.head.append(style);
 let busy=false,requests=[],signature="";
 async function run(body,source=panel) {
  if(busy)return;busy=true;error.textContent="";source.querySelector(".sky-invitation-error")?.remove();for(const b of source.querySelectorAll("button,select"))if(b!==close)b.disabled=true;
  try{await action({...body,request:crypto.randomUUID()});if(panel.open)panel.close();changed();}
  catch(e){if(source===panel)error.textContent=e.message;else{let p=source.querySelector(".sky-invitation-error");if(!p){p=document.createElement("p");p.className="sky-invitation-error";source.append(p);}p.textContent=e.message;}}
  finally{busy=false;for(const b of source.querySelectorAll("button,select"))b.disabled=false;}
 }
 function button(text,body,parent=content){const b=document.createElement("button");b.type="button";b.textContent=text;b.onclick=()=>void run(typeof body==="function"?body():body,parent===content?panel:parent);parent.append(b);return b;}
 function setRequests(next){requests=next??[];const nextSignature=JSON.stringify(requests);if(nextSignature===signature||busy)return;signature=nextSignature;invitations.replaceChildren();invitations.hidden=!requests.length;for(const r of requests){const row=document.createElement("div"),p=document.createElement("p");p.textContent=r.opponent+" vous d\u00e9fie.";row.append(p);button("Accepter",{action:"accept",invitation:r.id},row);button("Refuser",{action:"decline",invitation:r.id},row);invitations.append(row);}}
 async function open(){if(panel.open)return;dispatchEvent(new Event("blur"));content.textContent="Chargement\u2026";error.textContent="";panel.showModal();try{const data=await menu();content.replaceChildren();const huntTitle=document.createElement("h3");huntTitle.textContent="Prop Hunt";content.append(huntTitle);if(data.hunt&&data.hunt.phase==="waiting")button("Rejoindre ("+data.hunt.count+")",{action:"hunt_join",invitation:data.hunt.id});else if(!data.hunt||data.hunt.phase==="finished")button("Ouvrir une partie",{action:"hunt_create"});else{const p=document.createElement("p");p.textContent="Partie en cours.";content.append(p);}const duelTitle=document.createElement("h3");duelTitle.textContent="Duel";content.append(duelTitle);const select=document.createElement("select");select.setAttribute("aria-label","Adversaire");for(const name of data.characters){const o=document.createElement("option");o.value=name;o.textContent=name;select.append(o);}content.append(select);const challenge=button("D\u00e9fier",()=>({action:"duel",character:select.value}));challenge.disabled=!data.characters.length;setRequests(data.requests);}catch(e){content.replaceChildren();error.textContent=e.message;}}
 return {open,setRequests,run,dispose(){panel.remove();invitations.remove();style.remove();}};
}
